"""Single source of truth for the redis-rs-py compatibility matrix.

Every Redis/Valkey command we have decided to either implement, partially
implement, or explicitly defer gets exactly one entry here. The same data
drives:

  1. ``tests/compat/test_parity.py`` — runs every ``implemented`` entry
     through both clients and asserts equality.
  2. ``tests/compat/test_partial.py`` — runs every ``partial`` entry
     through the documented-divergence verifier.
  3. ``scripts/render_compat_matrix.py`` — renders the README markdown
     table.

Status values:

* ``implemented`` — full parity with redis-py.
* ``partial``     — covered, but with a documented difference. ``notes``
                    must explain the divergence.
* ``deferred``    — explicitly out of scope for v0.1. ``notes`` explains
                    why and (optionally) which version targets it.

Adding or moving an entry between buckets is a CHANGELOG-worthy event.
The pre-commit hook will fail the commit if the README block is stale.
"""

from __future__ import annotations

from typing import Final, Literal, TypedDict

Status = Literal["implemented", "partial", "deferred"]


class ManifestEntry(TypedDict):
    """One row in the compat matrix.

    Attributes:
        command:           Upstream Redis command name, e.g. ``"GET"``.
        method:            redis-py method name, e.g. ``"get"``. Must
                           match ``redis.Redis.<method>`` so the parity
                           tests can resolve it dynamically.
        family:            One of: strings, lists, hashes, sets, zsets,
                           streams, scripts, admin, pubsub, cluster,
                           sentinel, transactions.
        status:            ``implemented`` / ``partial`` / ``deferred``.
        notes:             Free-text divergence note. Required when
                           status is ``partial`` or ``deferred``.
        since_redis:       Earliest Valkey/Redis version that supports
                           this command (informational; renders as a
                           column in the README).
        since_redis_rs_py: Earliest redis-rs-py version that ships this
                           method (informational).
    """

    command: str
    method: str
    family: str
    status: Status
    notes: str
    since_redis: str
    since_redis_rs_py: str


# ---------------------------------------------------------------------------
# Strings (Plan 03)
# ---------------------------------------------------------------------------

STRING_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "GET",
        "method": "get",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SET",
        "method": "set",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "GETEX",
        "method": "getex",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "GETDEL",
        "method": "getdel",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "COPY",
        "method": "copy",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "INCR",
        "method": "incr",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "INCRBY",
        "method": "incrby",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "INCRBYFLOAT",
        "method": "incrbyfloat",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DECR",
        "method": "decr",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DECRBY",
        "method": "decrby",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "APPEND",
        "method": "append",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "STRLEN",
        "method": "strlen",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "MGET",
        "method": "mget",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "MSET",
        "method": "mset",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0.1",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "MSETNX",
        "method": "msetnx",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0.1",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SETRANGE",
        "method": "setrange",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "GETRANGE",
        "method": "getrange",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EXISTS",
        "method": "exists",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DEL",
        "method": "delete",
        "family": "strings",
        "status": "implemented",
        "notes": "redis-py exposes DEL as ``delete``",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "UNLINK",
        "method": "unlink",
        "family": "strings",
        "status": "implemented",
        "notes": "",
        "since_redis": "4.0",
        "since_redis_rs_py": "0.1",
    },
]


# ---------------------------------------------------------------------------
# Lists (Plan 04)
# ---------------------------------------------------------------------------

LIST_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "LPUSH",
        "method": "lpush",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RPUSH",
        "method": "rpush",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LPUSHX",
        "method": "lpushx",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RPUSHX",
        "method": "rpushx",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LPOP",
        "method": "lpop",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RPOP",
        "method": "rpop",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LMOVE",
        "method": "lmove",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BLMOVE",
        "method": "blmove",
        "family": "lists",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LMPOP",
        "method": "lmpop",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BLMPOP",
        "method": "blmpop",
        "family": "lists",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BLPOP",
        "method": "blpop",
        "family": "lists",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BRPOP",
        "method": "brpop",
        "family": "lists",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LPOS",
        "method": "lpos",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.0.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LRANGE",
        "method": "lrange",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LLEN",
        "method": "llen",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LREM",
        "method": "lrem",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LINDEX",
        "method": "lindex",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LSET",
        "method": "lset",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LINSERT",
        "method": "linsert",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LTRIM",
        "method": "ltrim",
        "family": "lists",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RPOPLPUSH",
        "method": "rpoplpush",
        "family": "lists",
        "status": "deferred",
        "notes": "deprecated upstream — use LMOVE",
        "since_redis": "1.2",
        "since_redis_rs_py": "—",
    },
    {
        "command": "BRPOPLPUSH",
        "method": "brpoplpush",
        "family": "lists",
        "status": "deferred",
        "notes": "deprecated upstream — use BLMOVE",
        "since_redis": "2.2",
        "since_redis_rs_py": "—",
    },
]


# ---------------------------------------------------------------------------
# Hashes (Plan 05)
# ---------------------------------------------------------------------------

HASH_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "HGET",
        "method": "hget",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HSET",
        "method": "hset",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HSETNX",
        "method": "hsetnx",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HMSET",
        "method": "hmset",
        "family": "hashes",
        "status": "deferred",
        "notes": "deprecated upstream — use HSET with mapping",
        "since_redis": "2.0",
        "since_redis_rs_py": "—",
    },
    {
        "command": "HGETALL",
        "method": "hgetall",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HDEL",
        "method": "hdel",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HINCRBY",
        "method": "hincrby",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HINCRBYFLOAT",
        "method": "hincrbyfloat",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HKEYS",
        "method": "hkeys",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HVALS",
        "method": "hvals",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HEXISTS",
        "method": "hexists",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HLEN",
        "method": "hlen",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HMGET",
        "method": "hmget",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HSCAN",
        "method": "hscan",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HRANDFIELD",
        "method": "hrandfield",
        "family": "hashes",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HEXPIRE",
        "method": "hexpire",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+ field TTL",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HPEXPIRE",
        "method": "hpexpire",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+ field TTL",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HEXPIREAT",
        "method": "hexpireat",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HPEXPIREAT",
        "method": "hpexpireat",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HEXPIRETIME",
        "method": "hexpiretime",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HPEXPIRETIME",
        "method": "hpexpiretime",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HTTL",
        "method": "httl",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HPTTL",
        "method": "hpttl",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "HPERSIST",
        "method": "hpersist",
        "family": "hashes",
        "status": "implemented",
        "notes": "Redis 7.4+",
        "since_redis": "7.4",
        "since_redis_rs_py": "0.1",
    },
]


# ---------------------------------------------------------------------------
# Sets (Plan 06)
# ---------------------------------------------------------------------------

SET_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "SADD",
        "method": "sadd",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SREM",
        "method": "srem",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SMEMBERS",
        "method": "smembers",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SISMEMBER",
        "method": "sismember",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SMISMEMBER",
        "method": "smismember",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SCARD",
        "method": "scard",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SINTER",
        "method": "sinter",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SINTERSTORE",
        "method": "sinterstore",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SINTERCARD",
        "method": "sintercard",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SUNION",
        "method": "sunion",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SUNIONSTORE",
        "method": "sunionstore",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SDIFF",
        "method": "sdiff",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SDIFFSTORE",
        "method": "sdiffstore",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SMOVE",
        "method": "smove",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SPOP",
        "method": "spop",
        "family": "sets",
        "status": "partial",
        "notes": "result order is server-defined; verifier asserts set equality, not list equality",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SRANDMEMBER",
        "method": "srandmember",
        "family": "sets",
        "status": "partial",
        "notes": "result order is server-defined; verifier asserts membership only",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SSCAN",
        "method": "sscan",
        "family": "sets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8",
        "since_redis_rs_py": "0.1",
    },
]


# ---------------------------------------------------------------------------
# Sorted sets (Plan 07)
# ---------------------------------------------------------------------------

ZSET_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "ZADD",
        "method": "zadd",
        "family": "zsets",
        "status": "implemented",
        "notes": "full NX/XX/GT/LT/CH/INCR matrix",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREM",
        "method": "zrem",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANGE",
        "method": "zrange",
        "family": "zsets",
        "status": "implemented",
        "notes": "BYSCORE/BYLEX/REV/LIMIT/WITHSCORES",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANGEBYSCORE",
        "method": "zrangebyscore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0.5",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREVRANGEBYSCORE",
        "method": "zrevrangebyscore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANGEBYLEX",
        "method": "zrangebylex",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREVRANGEBYLEX",
        "method": "zrevrangebylex",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANGESTORE",
        "method": "zrangestore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZINCRBY",
        "method": "zincrby",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZCARD",
        "method": "zcard",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZSCORE",
        "method": "zscore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZMSCORE",
        "method": "zmscore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANK",
        "method": "zrank",
        "family": "zsets",
        "status": "implemented",
        "notes": "WITHSCORE",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREVRANK",
        "method": "zrevrank",
        "family": "zsets",
        "status": "implemented",
        "notes": "WITHSCORE",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREMRANGEBYRANK",
        "method": "zremrangebyrank",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREMRANGEBYSCORE",
        "method": "zremrangebyscore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZREMRANGEBYLEX",
        "method": "zremrangebylex",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZCOUNT",
        "method": "zcount",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZLEXCOUNT",
        "method": "zlexcount",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZPOPMIN",
        "method": "zpopmin",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZPOPMAX",
        "method": "zpopmax",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BZPOPMIN",
        "method": "bzpopmin",
        "family": "zsets",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BZPOPMAX",
        "method": "bzpopmax",
        "family": "zsets",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZMPOP",
        "method": "zmpop",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BZMPOP",
        "method": "bzmpop",
        "family": "zsets",
        "status": "implemented",
        "notes": "uses lazy blocking conn",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZRANDMEMBER",
        "method": "zrandmember",
        "family": "zsets",
        "status": "partial",
        "notes": "result is non-deterministic without WITHSCORES; verifier asserts membership",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZSCAN",
        "method": "zscan",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZUNIONSTORE",
        "method": "zunionstore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZINTERSTORE",
        "method": "zinterstore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZDIFFSTORE",
        "method": "zdiffstore",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZUNION",
        "method": "zunion",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZINTER",
        "method": "zinter",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ZDIFF",
        "method": "zdiff",
        "family": "zsets",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
]


# ---------------------------------------------------------------------------
# Streams (Plan 08)
# ---------------------------------------------------------------------------

STREAM_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "XADD",
        "method": "xadd",
        "family": "streams",
        "status": "implemented",
        "notes": "NOMKSTREAM/MAXLEN/MINID/LIMIT/~",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XLEN",
        "method": "xlen",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XRANGE",
        "method": "xrange",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XREVRANGE",
        "method": "xrevrange",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XREAD",
        "method": "xread",
        "family": "streams",
        "status": "implemented",
        "notes": "BLOCK + COUNT",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XREADGROUP",
        "method": "xreadgroup",
        "family": "streams",
        "status": "implemented",
        "notes": "BLOCK + COUNT + NOACK",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XACK",
        "method": "xack",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XDEL",
        "method": "xdel",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XGROUP CREATE",
        "method": "xgroup_create",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XGROUP SETID",
        "method": "xgroup_setid",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XGROUP DESTROY",
        "method": "xgroup_destroy",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XGROUP DELCONSUMER",
        "method": "xgroup_delconsumer",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XGROUP CREATECONSUMER",
        "method": "xgroup_createconsumer",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XINFO STREAM",
        "method": "xinfo_stream",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XINFO GROUPS",
        "method": "xinfo_groups",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XINFO CONSUMERS",
        "method": "xinfo_consumers",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XTRIM",
        "method": "xtrim",
        "family": "streams",
        "status": "implemented",
        "notes": "MAXLEN/MINID/~",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XPENDING",
        "method": "xpending",
        "family": "streams",
        "status": "implemented",
        "notes": "summary + range forms",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XCLAIM",
        "method": "xclaim",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XAUTOCLAIM",
        "method": "xautoclaim",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "XSETID",
        "method": "xsetid",
        "family": "streams",
        "status": "implemented",
        "notes": "",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
]


# ---------------------------------------------------------------------------
# Scripts (Plan 09)
# ---------------------------------------------------------------------------

SCRIPT_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "EVAL",
        "method": "eval",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EVALSHA",
        "method": "evalsha",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EVAL_RO",
        "method": "eval_ro",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EVALSHA_RO",
        "method": "evalsha_ro",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SCRIPT LOAD",
        "method": "script_load",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SCRIPT EXISTS",
        "method": "script_exists",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SCRIPT FLUSH",
        "method": "script_flush",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FCALL",
        "method": "fcall",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FCALL_RO",
        "method": "fcall_ro",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION LOAD",
        "method": "function_load",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION DUMP",
        "method": "function_dump",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION FLUSH",
        "method": "function_flush",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION LIST",
        "method": "function_list",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION STATS",
        "method": "function_stats",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FUNCTION KILL",
        "method": "function_kill",
        "family": "scripts",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "register_script",
        "method": "register_script",
        "family": "scripts",
        "status": "deferred",
        "notes": "v0.1: use SCRIPT LOAD + EVALSHA directly",
        "since_redis": "2.6",
        "since_redis_rs_py": "—",
    },
]


# ---------------------------------------------------------------------------
# Admin / scan / keyspace (Plan 09)
# ---------------------------------------------------------------------------

ADMIN_ENTRIES: Final[list[ManifestEntry]] = [
    {
        "command": "SCAN",
        "method": "scan",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.8",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "SCAN_ITER",
        "method": "scan_iter",
        "family": "admin",
        "status": "implemented",
        "notes": "iterator wrapper",
        "since_redis": "2.8",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "KEYS",
        "method": "keys",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RANDOMKEY",
        "method": "randomkey",
        "family": "admin",
        "status": "partial",
        "notes": "result depends on keyspace; verifier asserts membership",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DBSIZE",
        "method": "dbsize",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FLUSHDB",
        "method": "flushdb",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "FLUSHALL",
        "method": "flushall",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "INFO",
        "method": "info",
        "family": "admin",
        "status": "partial",
        "notes": "values like ``uptime_in_seconds`` differ between calls; verifier asserts shape + key presence",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CONFIG GET",
        "method": "config_get",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CONFIG SET",
        "method": "config_set",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CONFIG RESETSTAT",
        "method": "config_resetstat",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CONFIG REWRITE",
        "method": "config_rewrite",
        "family": "admin",
        "status": "deferred",
        "notes": "requires writable redis.conf — not exercised in CI",
        "since_redis": "2.8",
        "since_redis_rs_py": "—",
    },
    {
        "command": "CLIENT GETNAME",
        "method": "client_getname",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT SETNAME",
        "method": "client_setname",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6.9",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT ID",
        "method": "client_id",
        "family": "admin",
        "status": "partial",
        "notes": "ID values differ across clients; verifier asserts type only",
        "since_redis": "5.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT INFO",
        "method": "client_info",
        "family": "admin",
        "status": "partial",
        "notes": "shape parity; values differ across clients",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT LIST",
        "method": "client_list",
        "family": "admin",
        "status": "partial",
        "notes": "shape parity; values differ across clients",
        "since_redis": "2.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT KILL",
        "method": "client_kill",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.4",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT PAUSE",
        "method": "client_pause",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "3.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT UNPAUSE",
        "method": "client_unpause",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "6.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT NO-EVICT",
        "method": "client_no_evict",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "CLIENT NO-TOUCH",
        "method": "client_no_touch",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "OBJECT ENCODING",
        "method": "object_encoding",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2.3",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "OBJECT IDLETIME",
        "method": "object_idletime",
        "family": "admin",
        "status": "partial",
        "notes": "wall-clock dependent; verifier asserts non-negative int",
        "since_redis": "2.2.3",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "OBJECT FREQ",
        "method": "object_freq",
        "family": "admin",
        "status": "partial",
        "notes": "requires LFU policy; skipped under default config",
        "since_redis": "4.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "OBJECT REFCOUNT",
        "method": "object_refcount",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2.3",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "MEMORY USAGE",
        "method": "memory_usage",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "4.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PING",
        "method": "ping",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "ECHO",
        "method": "echo",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "WAIT",
        "method": "wait",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "3.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "WAITAOF",
        "method": "waitaof",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "TIME",
        "method": "time",
        "family": "admin",
        "status": "partial",
        "notes": "wall-clock dependent; verifier asserts shape (sec, usec)",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "LASTSAVE",
        "method": "lastsave",
        "family": "admin",
        "status": "partial",
        "notes": "wall-clock dependent; verifier asserts type only",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BGSAVE",
        "method": "bgsave",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "BGREWRITEAOF",
        "method": "bgrewriteaof",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EXPIRE",
        "method": "expire",
        "family": "admin",
        "status": "implemented",
        "notes": "NX/XX/GT/LT flags",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PEXPIRE",
        "method": "pexpire",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EXPIREAT",
        "method": "expireat",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PEXPIREAT",
        "method": "pexpireat",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "EXPIRETIME",
        "method": "expiretime",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PEXPIRETIME",
        "method": "pexpiretime",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "7.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "TTL",
        "method": "ttl",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PTTL",
        "method": "pttl",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "PERSIST",
        "method": "persist",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.2",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RENAME",
        "method": "rename",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RENAMENX",
        "method": "renamenx",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "TYPE",
        "method": "type",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "1.0",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DUMP",
        "method": "dump",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "RESTORE",
        "method": "restore",
        "family": "admin",
        "status": "implemented",
        "notes": "",
        "since_redis": "2.6",
        "since_redis_rs_py": "0.1",
    },
    {
        "command": "DEBUG SLEEP",
        "method": "debug_sleep",
        "family": "admin",
        "status": "deferred",
        "notes": "test-only helper, not part of redis-py public surface",
        "since_redis": "1.0",
        "since_redis_rs_py": "—",
    },
    {
        "command": "MONITOR",
        "method": "monitor",
        "family": "admin",
        "status": "deferred",
        "notes": "v0.2; rarely used in production",
        "since_redis": "1.0",
        "since_redis_rs_py": "—",
    },
    {
        "command": "LATENCY HISTORY",
        "method": "latency_history",
        "family": "admin",
        "status": "deferred",
        "notes": "v0.2",
        "since_redis": "2.8.13",
        "since_redis_rs_py": "—",
    },
    {
        "command": "CLIENT TRACKING",
        "method": "client_tracking",
        "family": "admin",
        "status": "deferred",
        "notes": "v0.2 — caching is configured in Rust, not via this command",
        "since_redis": "6.0",
        "since_redis_rs_py": "—",
    },
]


# ---------------------------------------------------------------------------
# Master list
# ---------------------------------------------------------------------------

MANIFEST: Final[list[ManifestEntry]] = [
    *STRING_ENTRIES,
    *LIST_ENTRIES,
    *HASH_ENTRIES,
    *SET_ENTRIES,
    *ZSET_ENTRIES,
    *STREAM_ENTRIES,
    *SCRIPT_ENTRIES,
    *ADMIN_ENTRIES,
]


def by_status(status: Status) -> list[ManifestEntry]:
    """Return all entries matching a given status."""
    return [e for e in MANIFEST if e["status"] == status]


def by_family(family: str) -> list[ManifestEntry]:
    """Return all entries in a given command family."""
    return [e for e in MANIFEST if e["family"] == family]


def get_by_command(command: str) -> ManifestEntry:
    """Look up a single entry by uppercase command name."""
    for e in MANIFEST:
        if e["command"] == command:
            return e
    raise KeyError(command)


def _validate_manifest() -> None:
    """Fail-fast check run at import time.

    Catches the two classes of mistakes that would silently corrupt the
    matrix and the tests:

    * duplicate ``command`` keys (would shadow each other in lookups);
    * empty ``notes`` on a ``partial`` or ``deferred`` row.
    """
    seen: set[str] = set()
    for entry in MANIFEST:
        if entry["command"] in seen:
            raise RuntimeError(f"duplicate manifest command: {entry['command']}")
        seen.add(entry["command"])
        if entry["status"] in {"partial", "deferred"} and not entry["notes"]:
            raise RuntimeError(
                f"{entry['command']} is {entry['status']} but has no notes",
            )


_validate_manifest()
