# Type stubs for the _driver Rust extension module.
#
# Hand-maintained until pyo3-stub-gen becomes viable for our setup; new
# commands (plans 03-09) extend this file as they land.

import builtins
from collections.abc import AsyncIterator, Awaitable, Iterator
from typing import Any

# Alias so that stubs inside the class body (where `set` refers to the method)
# can still reference the builtin set type.
_Set = builtins.set

__version__: str

class RedisRsAwaitable:
    _asyncio_future_blocking: bool
    def __await__(self) -> RedisRsAwaitable: ...
    def __iter__(self) -> RedisRsAwaitable: ...
    def __next__(self) -> Any: ...
    def add_done_callback(
        self,
        fn_cb: Any,
        *,
        context: Any | None = ...,
    ) -> None: ...
    def cancel(self, msg: Any | None = ...) -> bool: ...
    def cancelled(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self) -> Any: ...
    def exception(self) -> Any: ...

class RedisRsDriver:
    @staticmethod
    def connect_standard(
        url: str,
        *,
        cache_max_size: int | None = ...,
        cache_ttl_secs: int | None = ...,
        ssl_ca_certs: bytes | None = ...,
        ssl_certfile: bytes | None = ...,
        ssl_keyfile: bytes | None = ...,
    ) -> RedisRsDriver: ...
    @property
    def connection_url(self) -> str: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def get(self, key: str) -> bytes | None: ...
    def aget(self, key: str) -> Awaitable[bytes | None]: ...
    # --- SET full matrix -------------------------------------------------
    def set(  # type: ignore[override]
        self,
        name: str,
        value: bytes,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        nx: bool = ...,
        xx: bool = ...,
        keepttl: bool = ...,
        get: bool = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
    ) -> bool | bytes | None: ...
    def aset(  # type: ignore[override]
        self,
        name: str,
        value: bytes,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        nx: bool = ...,
        xx: bool = ...,
        keepttl: bool = ...,
        get: bool = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
    ) -> Awaitable[bool | bytes | None]: ...

    # --- GET family ------------------------------------------------------
    def getex(
        self,
        name: str,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
        persist: bool = ...,
    ) -> bytes | None: ...
    def agetex(
        self,
        name: str,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
        persist: bool = ...,
    ) -> Awaitable[bytes | None]: ...
    def getdel(self, name: str) -> bytes | None: ...
    def agetdel(self, name: str) -> Awaitable[bytes | None]: ...
    def getrange(self, name: str, start: int, end: int) -> bytes: ...
    def agetrange(self, name: str, start: int, end: int) -> Awaitable[bytes]: ...
    def setrange(self, name: str, offset: int, value: bytes) -> int: ...
    def asetrange(self, name: str, offset: int, value: bytes) -> Awaitable[int]: ...
    def strlen(self, name: str) -> int: ...
    def astrlen(self, name: str) -> Awaitable[int]: ...
    def append(self, name: str, value: bytes) -> int: ...
    def aappend(self, name: str, value: bytes) -> Awaitable[int]: ...

    # --- MGET / MSET / MSETNX --------------------------------------------
    def mget(self, keys: list[str]) -> list[bytes | None]: ...
    def amget(self, keys: list[str]) -> Awaitable[list[bytes | None]]: ...
    def mset(self, mapping: dict[str, bytes]) -> None: ...
    def amset(self, mapping: dict[str, bytes]) -> Awaitable[None]: ...
    def msetnx(self, mapping: dict[str, bytes]) -> bool: ...
    def amsetnx(self, mapping: dict[str, bytes]) -> Awaitable[bool]: ...

    # --- INCR / DECR family ---------------------------------------------
    def incr(self, name: str) -> int: ...
    def aincr(self, name: str) -> Awaitable[int]: ...
    def incrby(self, name: str, amount: int) -> int: ...
    def aincrby(self, name: str, amount: int) -> Awaitable[int]: ...
    def incrbyfloat(self, name: str, amount: float) -> float: ...
    def aincrbyfloat(self, name: str, amount: float) -> Awaitable[float]: ...
    def decr(self, name: str) -> int: ...
    def adecr(self, name: str) -> Awaitable[int]: ...
    def decrby(self, name: str, amount: int) -> int: ...
    def adecrby(self, name: str, amount: int) -> Awaitable[int]: ...

    # --- EXISTS / UNLINK -------------------------------------------------
    def exists(self, *names: str) -> int: ...
    def aexists(self, *names: str) -> Awaitable[int]: ...
    def unlink(self, *names: str) -> int: ...
    def aunlink(self, *names: str) -> Awaitable[int]: ...

    # --- EXPIRE family + TTL --------------------------------------------
    def expire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def aexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def pexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def apexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def expireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def aexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def pexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def apexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def ttl(self, name: str) -> int: ...
    def attl(self, name: str) -> Awaitable[int]: ...
    def pttl(self, name: str) -> int: ...
    def apttl(self, name: str) -> Awaitable[int]: ...
    def expiretime(self, name: str) -> int: ...
    def aexpiretime(self, name: str) -> Awaitable[int]: ...
    def pexpiretime(self, name: str) -> int: ...
    def apexpiretime(self, name: str) -> Awaitable[int]: ...
    def persist(self, name: str) -> bool: ...
    def apersist(self, name: str) -> Awaitable[bool]: ...

    # --- RENAME / TYPE ---------------------------------------------------
    def rename(self, src: str, dst: str) -> None: ...
    def arename(self, src: str, dst: str) -> Awaitable[None]: ...
    def renamenx(self, src: str, dst: str) -> bool: ...
    def arenamenx(self, src: str, dst: str) -> Awaitable[bool]: ...
    def type(self, name: str) -> str: ...
    def atype(self, name: str) -> Awaitable[str]: ...
    def key_type(self, name: str) -> str: ...
    def akey_type(self, name: str) -> Awaitable[str]: ...

    # --- COPY ------------------------------------------------------------
    def copy(
        self,
        source: str,
        destination: str,
        *,
        db: int | None = ...,
        replace: bool = ...,
    ) -> bool: ...
    def acopy(
        self,
        source: str,
        destination: str,
        *,
        db: int | None = ...,
        replace: bool = ...,
    ) -> Awaitable[bool]: ...

    # --- DUMP / RESTORE --------------------------------------------------
    def dump(self, name: str) -> bytes | None: ...
    def adump(self, name: str) -> Awaitable[bytes | None]: ...
    def restore(
        self,
        name: str,
        ttl: int,
        value: bytes,
        *,
        replace: bool = ...,
        absttl: bool = ...,
        idletime: int | None = ...,
        frequency: int | None = ...,
    ) -> bool: ...
    def arestore(
        self,
        name: str,
        ttl: int,
        value: bytes,
        *,
        replace: bool = ...,
        absttl: bool = ...,
        idletime: int | None = ...,
        frequency: int | None = ...,
    ) -> Awaitable[bool]: ...
    def delete(self, *keys: str) -> int: ...
    def adelete(self, *keys: str) -> Awaitable[int]: ...
    def ping(self, *, message: str | None = ...) -> bool | bytes: ...
    def aping(self, *, message: str | None = ...) -> Awaitable[bool | bytes]: ...

    # --- LPUSH / RPUSH (variadic) ---------------------------------------
    def lpush(self, name: str, *values: bytes) -> int: ...
    def alpush(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def rpush(self, name: str, *values: bytes) -> int: ...
    def arpush(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def lpushx(self, name: str, *values: bytes) -> int: ...
    def alpushx(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def rpushx(self, name: str, *values: bytes) -> int: ...
    def arpushx(self, name: str, *values: bytes) -> Awaitable[int]: ...

    # --- LPOP / RPOP / LRANGE / LLEN ------------------------------------
    def lpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def alpop(self, name: str, count: int | None = ...) -> Awaitable[bytes | list[bytes] | None]: ...
    def rpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def arpop(self, name: str, count: int | None = ...) -> Awaitable[bytes | list[bytes] | None]: ...
    def lrange(self, name: str, start: int, end: int) -> list[bytes]: ...
    def alrange(self, name: str, start: int, end: int) -> Awaitable[list[bytes]]: ...
    def llen(self, name: str) -> int: ...
    def allen(self, name: str) -> Awaitable[int]: ...

    # --- LMOVE / LPOS ---------------------------------------------------
    def lmove(self, first_list: str, second_list: str, src: str, dest: str) -> bytes | None: ...
    def almove(self, first_list: str, second_list: str, src: str, dest: str) -> Awaitable[bytes | None]: ...
    def lpos(
        self,
        name: str,
        value: bytes,
        *,
        rank: int | None = ...,
        count: int | None = ...,
        maxlen: int | None = ...,
    ) -> int | list[int] | None: ...
    def alpos(
        self,
        name: str,
        value: bytes,
        *,
        rank: int | None = ...,
        count: int | None = ...,
        maxlen: int | None = ...,
    ) -> Awaitable[int | list[int] | None]: ...

    # --- LREM / LINDEX / LSET / LINSERT / LTRIM -------------------------
    def lrem(self, name: str, count: int, value: bytes) -> int: ...
    def alrem(self, name: str, count: int, value: bytes) -> Awaitable[int]: ...
    def lindex(self, name: str, index: int) -> bytes | None: ...
    def alindex(self, name: str, index: int) -> Awaitable[bytes | None]: ...
    def lset(self, name: str, index: int, value: bytes) -> None: ...
    def alset(self, name: str, index: int, value: bytes) -> Awaitable[None]: ...
    def linsert(self, name: str, where_: str, refvalue: bytes, value: bytes) -> int: ...
    def alinsert(self, name: str, where_: str, refvalue: bytes, value: bytes) -> Awaitable[int]: ...
    def ltrim(self, name: str, start: int, end: int) -> None: ...
    def altrim(self, name: str, start: int, end: int) -> Awaitable[None]: ...

    # --- LMPOP ----------------------------------------------------------
    def lmpop(
        self,
        keys: list[str],
        *,
        direction: str,
        count: int = ...,
    ) -> tuple[str, list[bytes]] | None: ...
    def almpop(
        self,
        keys: list[str],
        *,
        direction: str,
        count: int = ...,
    ) -> Awaitable[tuple[str, list[bytes]] | None]: ...

    # --- Blocking: BLPOP / BRPOP / BLMOVE / BLMPOP ----------------------
    def blpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def ablpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def brpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def abrpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def blmove(
        self,
        first_list: str,
        second_list: str,
        src: str,
        dest: str,
        timeout: float,
    ) -> bytes | None: ...
    def ablmove(
        self,
        first_list: str,
        second_list: str,
        src: str,
        dest: str,
        timeout: float,
    ) -> Awaitable[bytes | None]: ...
    def blmpop(
        self,
        *,
        timeout: float,
        keys: list[str],
        direction: str,
        count: int = ...,
    ) -> tuple[str, list[bytes]] | None: ...
    def ablmpop(
        self,
        *,
        timeout: float,
        keys: list[str],
        direction: str,
        count: int = ...,
    ) -> Awaitable[tuple[str, list[bytes]] | None]: ...

    # --- Hashes (Plan 05) ------------------------------------------------
    def hget(self, key: str, field: str) -> bytes | None: ...
    def ahget(self, key: str, field: str) -> Awaitable[bytes | None]: ...
    def hset(
        self,
        key: str,
        *items: str | bytes,
        mapping: dict[str, bytes] | None = ...,
    ) -> int: ...
    def ahset(
        self,
        key: str,
        *items: str | bytes,
        mapping: dict[str, bytes] | None = ...,
    ) -> Awaitable[int]: ...
    def hsetnx(self, key: str, field: str, value: bytes) -> bool: ...
    def ahsetnx(self, key: str, field: str, value: bytes) -> Awaitable[bool]: ...
    def hmset(self, key: str, mapping: dict[str, bytes]) -> None: ...
    def ahmset(self, key: str, mapping: dict[str, bytes]) -> Awaitable[None]: ...
    def hgetall(self, key: str) -> dict[bytes, bytes]: ...
    def ahgetall(self, key: str) -> Awaitable[dict[bytes, bytes]]: ...
    def hmget(self, key: str, *fields: str) -> list[bytes | None]: ...
    def ahmget(self, key: str, *fields: str) -> Awaitable[list[bytes | None]]: ...
    def hdel(self, key: str, *fields: str) -> int: ...
    def ahdel(self, key: str, *fields: str) -> Awaitable[int]: ...
    def hexists(self, key: str, field: str) -> bool: ...
    def ahexists(self, key: str, field: str) -> Awaitable[bool]: ...
    def hlen(self, key: str) -> int: ...
    def ahlen(self, key: str) -> Awaitable[int]: ...
    def hkeys(self, key: str) -> list[bytes]: ...
    def ahkeys(self, key: str) -> Awaitable[list[bytes]]: ...
    def hvals(self, key: str) -> list[bytes]: ...
    def ahvals(self, key: str) -> Awaitable[list[bytes]]: ...
    def hincrby(self, key: str, field: str, amount: int) -> int: ...
    def ahincrby(self, key: str, field: str, amount: int) -> Awaitable[int]: ...
    def hincrbyfloat(self, key: str, field: str, amount: float) -> float: ...
    def ahincrbyfloat(self, key: str, field: str, amount: float) -> Awaitable[float]: ...
    def hrandfield(
        self,
        key: str,
        count: int | None = ...,
        withvalues: bool = ...,
    ) -> bytes | list[bytes] | list[tuple[bytes, bytes]] | None: ...
    def ahrandfield(
        self,
        key: str,
        count: int | None = ...,
        withvalues: bool = ...,
    ) -> Awaitable[bytes | list[bytes] | list[tuple[bytes, bytes]] | None]: ...
    def hscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        novalues: bool = ...,
    ) -> tuple[int, dict[bytes, bytes] | list[bytes]]: ...
    def ahscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        novalues: bool = ...,
    ) -> Awaitable[tuple[int, dict[bytes, bytes] | list[bytes]]]: ...
    # Hash-field TTL family (Redis 7.4+)
    def hexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hpexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahpexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hpexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahpexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hexpiretime(self, key: str, fields: list[str]) -> list[int]: ...
    def ahexpiretime(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpexpiretime(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpexpiretime(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def httl(self, key: str, fields: list[str]) -> list[int]: ...
    def ahttl(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpttl(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpttl(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpersist(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpersist(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...

    # --- Sets (Plan 06) --------------------------------------------------
    def sadd(self, key: str, *members: bytes) -> int: ...
    def asadd(self, key: str, *members: bytes) -> Awaitable[int]: ...
    def srem(self, key: str, *members: bytes) -> int: ...
    def asrem(self, key: str, *members: bytes) -> Awaitable[int]: ...
    def smembers(self, key: str) -> _Set[bytes]: ...
    def asmembers(self, key: str) -> Awaitable[_Set[bytes]]: ...
    def scard(self, key: str) -> int: ...
    def ascard(self, key: str) -> Awaitable[int]: ...
    def sismember(self, key: str, member: bytes) -> bool: ...
    def asismember(self, key: str, member: bytes) -> Awaitable[bool]: ...
    def smismember(self, key: str, *members: bytes) -> list[bool]: ...
    def asmismember(self, key: str, *members: bytes) -> Awaitable[list[bool]]: ...
    def spop(self, key: str, count: int | None = ...) -> bytes | _Set[bytes] | None: ...
    def aspop(self, key: str, count: int | None = ...) -> Awaitable[bytes | _Set[bytes] | None]: ...
    def srandmember(self, key: str, count: int | None = ...) -> bytes | _Set[bytes] | list[bytes] | None: ...
    def asrandmember(
        self, key: str, count: int | None = ...
    ) -> Awaitable[bytes | _Set[bytes] | list[bytes] | None]: ...
    def sinter(self, *keys: str) -> _Set[bytes]: ...
    def asinter(self, *keys: str) -> Awaitable[_Set[bytes]]: ...
    def sunion(self, *keys: str) -> _Set[bytes]: ...
    def asunion(self, *keys: str) -> Awaitable[_Set[bytes]]: ...
    def sdiff(self, *keys: str) -> _Set[bytes]: ...
    def asdiff(self, *keys: str) -> Awaitable[_Set[bytes]]: ...
    def sinterstore(self, destination: str, *keys: str) -> int: ...
    def asinterstore(self, destination: str, *keys: str) -> Awaitable[int]: ...
    def sunionstore(self, destination: str, *keys: str) -> int: ...
    def asunionstore(self, destination: str, *keys: str) -> Awaitable[int]: ...
    def sdiffstore(self, destination: str, *keys: str) -> int: ...
    def asdiffstore(self, destination: str, *keys: str) -> Awaitable[int]: ...
    def sintercard(self, *keys: str, limit: int | None = ...) -> int: ...
    def asintercard(self, *keys: str, limit: int | None = ...) -> Awaitable[int]: ...
    def smove(self, source: str, destination: str, member: bytes) -> bool: ...
    def asmove(self, source: str, destination: str, member: bytes) -> Awaitable[bool]: ...
    def sscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
    ) -> tuple[int, _Set[bytes]]: ...
    def asscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
    ) -> Awaitable[tuple[int, _Set[bytes]]]: ...

    # --- Sorted sets (Plan 07) -------------------------------------------
    def zadd(
        self,
        key: str,
        *,
        mapping: dict[str | bytes, float],
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
        ch: bool = ...,
        incr: bool = ...,
    ) -> int | float | None: ...
    def azadd(
        self,
        key: str,
        *,
        mapping: dict[str | bytes, float],
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
        ch: bool = ...,
        incr: bool = ...,
    ) -> Awaitable[int | float | None]: ...
    def zrem(self, key: str, *members: bytes) -> int: ...
    def azrem(self, key: str, *members: bytes) -> Awaitable[int]: ...
    def zrange(
        self,
        key: str,
        start: int | str | bytes,
        stop: int | str | bytes,
        *,
        desc: bool = ...,
        byscore: bool = ...,
        bylex: bool = ...,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azrange(
        self,
        key: str,
        start: int | str | bytes,
        stop: int | str | bytes,
        *,
        desc: bool = ...,
        byscore: bool = ...,
        bylex: bool = ...,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zrangestore(
        self,
        destination: str,
        source: str,
        start: int | str | bytes,
        stop: int | str | bytes,
        *,
        desc: bool = ...,
        byscore: bool = ...,
        bylex: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> int: ...
    def azrangestore(
        self,
        destination: str,
        source: str,
        start: int | str | bytes,
        stop: int | str | bytes,
        *,
        desc: bool = ...,
        byscore: bool = ...,
        bylex: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[int]: ...
    def zrangebyscore(
        self,
        key: str,
        min: str,
        max: str,
        *,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azrangebyscore(
        self,
        key: str,
        min: str,
        max: str,
        *,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zrevrangebyscore(
        self,
        key: str,
        max: str,
        min: str,
        *,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azrevrangebyscore(
        self,
        key: str,
        max: str,
        min: str,
        *,
        withscores: bool = ...,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zrangebylex(
        self,
        key: str,
        min: str,
        max: str,
        *,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> list[bytes]: ...
    def azrangebylex(
        self,
        key: str,
        min: str,
        max: str,
        *,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[list[bytes]]: ...
    def zrevrangebylex(
        self,
        key: str,
        max: str,
        min: str,
        *,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> list[bytes]: ...
    def azrevrangebylex(
        self,
        key: str,
        max: str,
        min: str,
        *,
        offset: int | None = ...,
        num: int | None = ...,
    ) -> Awaitable[list[bytes]]: ...
    def zincrby(self, key: str, amount: float, member: bytes) -> float: ...
    def azincrby(self, key: str, amount: float, member: bytes) -> Awaitable[float]: ...
    def zcard(self, key: str) -> int: ...
    def azcard(self, key: str) -> Awaitable[int]: ...
    def zscore(self, key: str, member: bytes) -> float | None: ...
    def azscore(self, key: str, member: bytes) -> Awaitable[float | None]: ...
    def zmscore(self, key: str, *members: bytes) -> list[float | None]: ...
    def azmscore(self, key: str, *members: bytes) -> Awaitable[list[float | None]]: ...
    def zrank(self, key: str, member: bytes, *, withscore: bool = ...) -> int | tuple[int, float] | None: ...
    def azrank(
        self, key: str, member: bytes, *, withscore: bool = ...
    ) -> Awaitable[int | tuple[int, float] | None]: ...
    def zrevrank(self, key: str, member: bytes, *, withscore: bool = ...) -> int | tuple[int, float] | None: ...
    def azrevrank(
        self, key: str, member: bytes, *, withscore: bool = ...
    ) -> Awaitable[int | tuple[int, float] | None]: ...
    def zremrangebyrank(self, key: str, start: int, stop: int) -> int: ...
    def azremrangebyrank(self, key: str, start: int, stop: int) -> Awaitable[int]: ...
    def zremrangebyscore(self, key: str, min: str, max: str) -> int: ...
    def azremrangebyscore(self, key: str, min: str, max: str) -> Awaitable[int]: ...
    def zremrangebylex(self, key: str, min: str, max: str) -> int: ...
    def azremrangebylex(self, key: str, min: str, max: str) -> Awaitable[int]: ...
    def zcount(self, key: str, min: str, max: str) -> int: ...
    def azcount(self, key: str, min: str, max: str) -> Awaitable[int]: ...
    def zlexcount(self, key: str, min: str, max: str) -> int: ...
    def azlexcount(self, key: str, min: str, max: str) -> Awaitable[int]: ...
    def zpopmin(self, key: str, *, count: int = ...) -> list[tuple[bytes, float]]: ...
    def azpopmin(self, key: str, *, count: int = ...) -> Awaitable[list[tuple[bytes, float]]]: ...
    def zpopmax(self, key: str, *, count: int = ...) -> list[tuple[bytes, float]]: ...
    def azpopmax(self, key: str, *, count: int = ...) -> Awaitable[list[tuple[bytes, float]]]: ...
    def zmpop(self, *keys: str, direction: str, count: int = ...) -> tuple[str, list[tuple[bytes, float]]] | None: ...
    def azmpop(
        self, *keys: str, direction: str, count: int = ...
    ) -> Awaitable[tuple[str, list[tuple[bytes, float]]] | None]: ...
    def bzpopmin(self, *keys: str, timeout: float) -> tuple[bytes, bytes, float] | None: ...
    def abzpopmin(self, *keys: str, timeout: float) -> Awaitable[tuple[bytes, bytes, float] | None]: ...
    def bzpopmax(self, *keys: str, timeout: float) -> tuple[bytes, bytes, float] | None: ...
    def abzpopmax(self, *keys: str, timeout: float) -> Awaitable[tuple[bytes, bytes, float] | None]: ...
    def bzmpop(
        self, *keys: str, direction: str, timeout: float, count: int = ...
    ) -> tuple[str, list[tuple[bytes, float]]] | None: ...
    def abzmpop(
        self, *keys: str, direction: str, timeout: float, count: int = ...
    ) -> Awaitable[tuple[str, list[tuple[bytes, float]]] | None]: ...
    def zrandmember(
        self, key: str, count: int | None = ..., withscores: bool = ...
    ) -> bytes | list[bytes] | list[tuple[bytes, float]] | None: ...
    def azrandmember(
        self, key: str, count: int | None = ..., withscores: bool = ...
    ) -> Awaitable[bytes | list[bytes] | list[tuple[bytes, float]] | None]: ...
    def zscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
    ) -> tuple[int, list[tuple[bytes, float]]]: ...
    def azscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
    ) -> Awaitable[tuple[int, list[tuple[bytes, float]]]]: ...
    def zunion(
        self,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
        withscores: bool = ...,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azunion(
        self,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
        withscores: bool = ...,
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zinter(
        self,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
        withscores: bool = ...,
    ) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azinter(
        self,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
        withscores: bool = ...,
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zdiff(self, *, keys: list[str], withscores: bool = ...) -> list[bytes] | list[tuple[bytes, float]]: ...
    def azdiff(
        self, *, keys: list[str], withscores: bool = ...
    ) -> Awaitable[list[bytes] | list[tuple[bytes, float]]]: ...
    def zunionstore(
        self,
        destination: str,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
    ) -> int: ...
    def azunionstore(
        self,
        destination: str,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
    ) -> Awaitable[int]: ...
    def zinterstore(
        self,
        destination: str,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
    ) -> int: ...
    def azinterstore(
        self,
        destination: str,
        *,
        keys: list[str],
        weights: list[float] | None = ...,
        aggregate: str | None = ...,
    ) -> Awaitable[int]: ...
    def zdiffstore(self, destination: str, *, keys: list[str]) -> int: ...
    def azdiffstore(self, destination: str, *, keys: list[str]) -> Awaitable[int]: ...
    def zintercard(self, *, keys: list[str], limit: int | None = ...) -> int: ...
    def azintercard(self, *, keys: list[str], limit: int | None = ...) -> Awaitable[int]: ...

    # --- Streams (Plan 08) ---------------------------------------------
    def xadd(
        self,
        key: str,
        id: str,
        fields: list[tuple[str, bytes]],
        *,
        nomkstream: bool = ...,
        maxlen: int | None = ...,
        minid: str | None = ...,
        approximate: bool = ...,
        limit: int | None = ...,
    ) -> str | None: ...
    def axadd(
        self,
        key: str,
        id: str,
        fields: list[tuple[str, bytes]],
        *,
        nomkstream: bool = ...,
        maxlen: int | None = ...,
        minid: str | None = ...,
        approximate: bool = ...,
        limit: int | None = ...,
    ) -> Awaitable[str | None]: ...
    def xlen(self, key: str) -> int: ...
    def axlen(self, key: str) -> Awaitable[int]: ...
    def xdel(self, key: str, *ids: str) -> int: ...
    def axdel(self, key: str, *ids: str) -> Awaitable[int]: ...
    def xack(self, key: str, group: str, *ids: str) -> int: ...
    def axack(self, key: str, group: str, *ids: str) -> Awaitable[int]: ...
    def xrange(
        self, key: str, min: str, max: str, *, count: int | None = ...
    ) -> list[tuple[bytes, dict[bytes, bytes]]]: ...
    def axrange(
        self, key: str, min: str, max: str, *, count: int | None = ...
    ) -> Awaitable[list[tuple[bytes, dict[bytes, bytes]]]]: ...
    def xrevrange(
        self, key: str, max: str, min: str, *, count: int | None = ...
    ) -> list[tuple[bytes, dict[bytes, bytes]]]: ...
    def axrevrange(
        self, key: str, max: str, min: str, *, count: int | None = ...
    ) -> Awaitable[list[tuple[bytes, dict[bytes, bytes]]]]: ...
    def xread(
        self,
        streams: dict[str, str],
        *,
        count: int | None = ...,
        block: int | None = ...,
    ) -> dict[bytes, list[tuple[bytes, dict[bytes, bytes]]]] | None: ...
    def axread(
        self,
        streams: dict[str, str],
        *,
        count: int | None = ...,
        block: int | None = ...,
    ) -> Awaitable[dict[bytes, list[tuple[bytes, dict[bytes, bytes]]]] | None]: ...
    def xreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[str, str],
        *,
        count: int | None = ...,
        block: int | None = ...,
        noack: bool = ...,
    ) -> dict[bytes, list[tuple[bytes, dict[bytes, bytes]]]] | None: ...
    def axreadgroup(
        self,
        group: str,
        consumer: str,
        streams: dict[str, str],
        *,
        count: int | None = ...,
        block: int | None = ...,
        noack: bool = ...,
    ) -> Awaitable[dict[bytes, list[tuple[bytes, dict[bytes, bytes]]]] | None]: ...
    def xgroup_create(
        self,
        key: str,
        group: str,
        *,
        id: str = ...,
        mkstream: bool = ...,
        entries_read: int | None = ...,
    ) -> None: ...
    def axgroup_create(
        self,
        key: str,
        group: str,
        *,
        id: str = ...,
        mkstream: bool = ...,
        entries_read: int | None = ...,
    ) -> Awaitable[None]: ...
    def xgroup_setid(self, key: str, group: str, *, id: str, entries_read: int | None = ...) -> None: ...
    def axgroup_setid(self, key: str, group: str, *, id: str, entries_read: int | None = ...) -> Awaitable[None]: ...
    def xgroup_destroy(self, key: str, group: str) -> int: ...
    def axgroup_destroy(self, key: str, group: str) -> Awaitable[int]: ...
    def xgroup_createconsumer(self, key: str, group: str, consumer: str) -> int: ...
    def axgroup_createconsumer(self, key: str, group: str, consumer: str) -> Awaitable[int]: ...
    def xgroup_delconsumer(self, key: str, group: str, consumer: str) -> int: ...
    def axgroup_delconsumer(self, key: str, group: str, consumer: str) -> Awaitable[int]: ...
    def xinfo_stream(self, key: str, *, full: bool = ...) -> dict[bytes, Any]: ...
    def axinfo_stream(self, key: str, *, full: bool = ...) -> Awaitable[dict[bytes, Any]]: ...
    def xinfo_groups(self, key: str) -> list[dict[bytes, Any]]: ...
    def axinfo_groups(self, key: str) -> Awaitable[list[dict[bytes, Any]]]: ...
    def xinfo_consumers(self, key: str, group: str) -> list[dict[bytes, Any]]: ...
    def axinfo_consumers(self, key: str, group: str) -> Awaitable[list[dict[bytes, Any]]]: ...
    def xtrim(
        self,
        key: str,
        *,
        maxlen: int | None = ...,
        minid: str | None = ...,
        approximate: bool = ...,
        limit: int | None = ...,
    ) -> int: ...
    def axtrim(
        self,
        key: str,
        *,
        maxlen: int | None = ...,
        minid: str | None = ...,
        approximate: bool = ...,
        limit: int | None = ...,
    ) -> Awaitable[int]: ...
    def xpending(
        self,
        key: str,
        group: str,
        *,
        idle: int | None = ...,
        min: str | None = ...,
        max: str | None = ...,
        count: int | None = ...,
        consumer: str | None = ...,
    ) -> tuple[int, bytes | None, bytes | None, list[tuple[bytes, int]]] | list[dict[bytes, Any]]: ...
    def axpending(
        self,
        key: str,
        group: str,
        *,
        idle: int | None = ...,
        min: str | None = ...,
        max: str | None = ...,
        count: int | None = ...,
        consumer: str | None = ...,
    ) -> Awaitable[tuple[int, bytes | None, bytes | None, list[tuple[bytes, int]]] | list[dict[bytes, Any]]]: ...
    def xclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        *,
        min_idle_time: int,
        message_ids: list[str],
        idle: int | None = ...,
        time: int | None = ...,
        retrycount: int | None = ...,
        force: bool = ...,
        justid: bool = ...,
    ) -> list[tuple[bytes, dict[bytes, bytes]]] | list[bytes]: ...
    def axclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        *,
        min_idle_time: int,
        message_ids: list[str],
        idle: int | None = ...,
        time: int | None = ...,
        retrycount: int | None = ...,
        force: bool = ...,
        justid: bool = ...,
    ) -> Awaitable[list[tuple[bytes, dict[bytes, bytes]]] | list[bytes]]: ...
    def xautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        *,
        min_idle_time: int,
        start_id: str = ...,
        count: int = ...,
        justid: bool = ...,
    ) -> tuple[
        bytes,
        list[tuple[bytes, dict[bytes, bytes]]] | list[bytes],
        list[bytes],
    ]: ...
    def axautoclaim(
        self,
        key: str,
        group: str,
        consumer: str,
        *,
        min_idle_time: int,
        start_id: str = ...,
        count: int = ...,
        justid: bool = ...,
    ) -> Awaitable[
        tuple[
            bytes,
            list[tuple[bytes, dict[bytes, bytes]]] | list[bytes],
            list[bytes],
        ]
    ]: ...
    def xsetid(
        self,
        key: str,
        id: str,
        *,
        entries_added: int | None = ...,
        max_deleted_entry_id: str | None = ...,
    ) -> None: ...
    def axsetid(
        self,
        key: str,
        id: str,
        *,
        entries_added: int | None = ...,
        max_deleted_entry_id: str | None = ...,
    ) -> Awaitable[None]: ...

    # --- Scripts (Plan 09) -------------------------------------------
    def eval(self, script: str, keys: list[str], args: list[bytes]) -> Any: ...
    def aeval(self, script: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def evalsha(self, sha: str, keys: list[str], args: list[bytes]) -> Any: ...
    def aevalsha(self, sha: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def eval_ro(self, script: str, keys: list[str], args: list[bytes]) -> Any: ...
    def aeval_ro(self, script: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def evalsha_ro(self, sha: str, keys: list[str], args: list[bytes]) -> Any: ...
    def aevalsha_ro(self, sha: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def script_load(self, script: str) -> str: ...
    def ascript_load(self, script: str) -> Awaitable[str]: ...
    def script_exists(self, *shas: str) -> list[bool]: ...
    def ascript_exists(self, *shas: str) -> Awaitable[list[bool]]: ...
    def script_flush(self, *, mode: str | None = ...) -> None: ...
    def ascript_flush(self, *, mode: str | None = ...) -> Awaitable[None]: ...
    def script_kill(self) -> None: ...
    def ascript_kill(self) -> Awaitable[None]: ...
    def fcall(self, function: str, keys: list[str], args: list[bytes]) -> Any: ...
    def afcall(self, function: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def fcall_ro(self, function: str, keys: list[str], args: list[bytes]) -> Any: ...
    def afcall_ro(self, function: str, keys: list[str], args: list[bytes]) -> Awaitable[Any]: ...
    def function_load(self, code: str, *, replace: bool = ...) -> str: ...
    def afunction_load(self, code: str, *, replace: bool = ...) -> Awaitable[str]: ...
    def function_delete(self, library: str) -> None: ...
    def afunction_delete(self, library: str) -> Awaitable[None]: ...
    def function_dump(self) -> bytes: ...
    def afunction_dump(self) -> Awaitable[bytes]: ...
    def function_flush(self, *, mode: str | None = ...) -> None: ...
    def afunction_flush(self, *, mode: str | None = ...) -> Awaitable[None]: ...
    def function_list(self, *, library: str | None = ..., withcode: bool = ...) -> list[Any]: ...
    def afunction_list(self, *, library: str | None = ..., withcode: bool = ...) -> Awaitable[list[Any]]: ...
    def function_stats(self) -> Any: ...
    def afunction_stats(self) -> Awaitable[Any]: ...
    def function_kill(self) -> None: ...
    def afunction_kill(self) -> Awaitable[None]: ...
    def function_restore(self, dump: bytes, *, policy: str | None = ...) -> None: ...
    def afunction_restore(self, dump: bytes, *, policy: str | None = ...) -> Awaitable[None]: ...

    # --- Admin / introspection (Plan 09) --------------------------------
    def scan(
        self,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        type: str | None = ...,
    ) -> tuple[int, list[bytes]]: ...
    def ascan(
        self,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        type: str | None = ...,
    ) -> Awaitable[tuple[int, list[bytes]]]: ...
    # scan_iter / scan_iter_async are attached at __init__ time — see _scan_iter.py.
    def scan_iter(
        self,
        *,
        match: str | None = ...,
        count: int | None = ...,
        type: str | None = ...,
    ) -> Iterator[bytes]: ...
    def scan_iter_async(
        self,
        *,
        match: str | None = ...,
        count: int | None = ...,
        type: str | None = ...,
    ) -> AsyncIterator[bytes]: ...
    def keys(self, pattern: str) -> list[bytes]: ...
    def akeys(self, pattern: str) -> Awaitable[list[bytes]]: ...
    def randomkey(self) -> bytes | None: ...
    def arandomkey(self) -> Awaitable[bytes | None]: ...
    def dbsize(self) -> int: ...
    def adbsize(self) -> Awaitable[int]: ...
    def flushdb(self, *, asynchronous: bool = ...) -> None: ...
    def aflushdb(self, *, asynchronous: bool = ...) -> Awaitable[None]: ...
    def flushall(self, *, asynchronous: bool = ...) -> None: ...
    def aflushall(self, *, asynchronous: bool = ...) -> Awaitable[None]: ...
    def select(self, db_index: int) -> bool: ...
    def info(self, *, section: str | None = ...) -> bytes: ...
    def ainfo(self, *, section: str | None = ...) -> Awaitable[bytes]: ...
    def config_get(self, parameter: str) -> dict[bytes, bytes]: ...
    def aconfig_get(self, parameter: str) -> Awaitable[dict[bytes, bytes]]: ...
    def config_set(
        self,
        name_or_mapping: str | dict[str, str],
        value: str | None = ...,
    ) -> None: ...
    def aconfig_set(
        self,
        name_or_mapping: str | dict[str, str],
        value: str | None = ...,
    ) -> Awaitable[None]: ...
    def config_resetstat(self) -> None: ...
    def aconfig_resetstat(self) -> Awaitable[None]: ...
    def config_rewrite(self) -> None: ...
    def aconfig_rewrite(self) -> Awaitable[None]: ...
    def client_id(self) -> int: ...
    def aclient_id(self) -> Awaitable[int]: ...
    def client_getname(self) -> bytes | None: ...
    def aclient_getname(self) -> Awaitable[bytes | None]: ...
    def client_setname(self, name: str) -> None: ...
    def aclient_setname(self, name: str) -> Awaitable[None]: ...
    def client_info(self) -> bytes: ...
    def aclient_info(self) -> Awaitable[bytes]: ...
    def client_list(
        self,
        *,
        client_type: str | None = ...,
        client_id: list[int] | None = ...,
    ) -> list[dict[bytes, bytes]]: ...
    def aclient_list(
        self,
        *,
        client_type: str | None = ...,
        client_id: list[int] | None = ...,
    ) -> Awaitable[list[dict[bytes, bytes]]]: ...
    def client_kill(
        self,
        *,
        addr: str | None = ...,
        laddr: str | None = ...,
        client_id: int | None = ...,
        client_type: str | None = ...,
        user: str | None = ...,
        skipme: bool | None = ...,
        maxage: int | None = ...,
    ) -> int: ...
    def aclient_kill(
        self,
        *,
        addr: str | None = ...,
        laddr: str | None = ...,
        client_id: int | None = ...,
        client_type: str | None = ...,
        user: str | None = ...,
        skipme: bool | None = ...,
        maxage: int | None = ...,
    ) -> Awaitable[int]: ...
    def client_pause(self, timeout_ms: int, *, all: bool = ...) -> None: ...
    def aclient_pause(self, timeout_ms: int, *, all: bool = ...) -> Awaitable[None]: ...
    def client_unpause(self) -> None: ...
    def aclient_unpause(self) -> Awaitable[None]: ...
    def client_no_evict(self, *, mode: str) -> None: ...
    def aclient_no_evict(self, *, mode: str) -> Awaitable[None]: ...
    def client_no_touch(self, *, mode: str) -> None: ...
    def aclient_no_touch(self, *, mode: str) -> Awaitable[None]: ...
    def object_encoding(self, key: str) -> bytes | None: ...
    def aobject_encoding(self, key: str) -> Awaitable[bytes | None]: ...
    def object_idletime(self, key: str) -> int | None: ...
    def aobject_idletime(self, key: str) -> Awaitable[int | None]: ...
    def object_freq(self, key: str) -> int | None: ...
    def aobject_freq(self, key: str) -> Awaitable[int | None]: ...
    def object_refcount(self, key: str) -> int | None: ...
    def aobject_refcount(self, key: str) -> Awaitable[int | None]: ...
    def object_help(self) -> list[bytes]: ...
    def aobject_help(self) -> Awaitable[list[bytes]]: ...
    def memory_usage(self, key: str, *, samples: int | None = ...) -> int | None: ...
    def amemory_usage(self, key: str, *, samples: int | None = ...) -> Awaitable[int | None]: ...
    def echo(self, message: str | bytes) -> bytes: ...
    def aecho(self, message: str | bytes) -> Awaitable[bytes]: ...
    def wait(self, *, numreplicas: int, timeout: int) -> int: ...
    def await_(self, *, numreplicas: int, timeout: int) -> Awaitable[int]: ...
    def waitaof(self, *, numlocal: int, numreplicas: int, timeout: int) -> Any: ...
    def awaitaof(self, *, numlocal: int, numreplicas: int, timeout: int) -> Awaitable[Any]: ...
    def time(self) -> tuple[str, str] | None: ...
    def atime(self) -> Awaitable[tuple[str, str] | None]: ...
    def lastsave(self) -> int: ...
    def alastsave(self) -> Awaitable[int]: ...
    def bgsave(self, *, schedule: bool = ...) -> bytes: ...
    def abgsave(self, *, schedule: bool = ...) -> Awaitable[bytes]: ...
    def bgrewriteaof(self) -> bytes: ...
    def abgrewriteaof(self) -> Awaitable[bytes]: ...
    def debug_sleep(self, seconds: float) -> None: ...
    def adebug_sleep(self, seconds: float) -> Awaitable[None]: ...

    # --- Test-only -----------------------------------------------------
    def _blocking_initialised(self) -> bool: ...

# Internal test helpers — exported but underscore-prefixed.
def _test_resolved_bytes(b: bytes) -> RedisRsAwaitable: ...
def _test_resolved_none() -> RedisRsAwaitable: ...
def _test_resolved_int(n: int) -> RedisRsAwaitable: ...
def _test_delayed_bytes(b: bytes, delay_ms: int) -> RedisRsAwaitable: ...
def _test_pending() -> RedisRsAwaitable: ...
def _test_dropped() -> RedisRsAwaitable: ...
def _test_error(msg: str) -> RedisRsAwaitable: ...
def _test_server_error(msg: str) -> RedisRsAwaitable: ...

class exceptions:
    class RedisError(Exception): ...
    class ConnectionError(RedisError): ...
    class TimeoutError(ConnectionError): ...
    class BusyLoadingError(ConnectionError): ...
    class AuthenticationError(ConnectionError): ...
    class AuthenticationWrongNumberOfArgsError(AuthenticationError): ...
    class MasterDownError(ConnectionError): ...
    class ResponseError(RedisError): ...
    class DataError(RedisError): ...
    class InvalidResponse(RedisError): ...
    class OutOfMemoryError(ResponseError): ...
    class NoScriptError(ResponseError): ...
    class ExecAbortError(ResponseError): ...
    class ReadOnlyError(ResponseError): ...
    class NoPermissionError(ResponseError): ...
    class ModuleError(ResponseError): ...
    class LockError(RedisError): ...
    class LockNotOwnedError(LockError): ...
    class WatchError(RedisError): ...
    class PubSubError(RedisError): ...
    class SlaveError(RedisError): ...
    class ClusterError(RedisError): ...
    class ClusterDownError(ResponseError, ClusterError): ...
    class ClusterCrossSlotError(ResponseError, ClusterError): ...
    class MovedError(ClusterError): ...
    class AskError(ClusterError): ...
    class TryAgainError(ClusterError): ...

# Top-level alias attrs (registered alongside the submodule):
RedisError = exceptions.RedisError
ConnectionError = exceptions.ConnectionError
TimeoutError = exceptions.TimeoutError
BusyLoadingError = exceptions.BusyLoadingError
AuthenticationError = exceptions.AuthenticationError
AuthenticationWrongNumberOfArgsError = exceptions.AuthenticationWrongNumberOfArgsError
MasterDownError = exceptions.MasterDownError
ResponseError = exceptions.ResponseError
DataError = exceptions.DataError
InvalidResponse = exceptions.InvalidResponse
OutOfMemoryError = exceptions.OutOfMemoryError
NoScriptError = exceptions.NoScriptError
ExecAbortError = exceptions.ExecAbortError
ReadOnlyError = exceptions.ReadOnlyError
NoPermissionError = exceptions.NoPermissionError
ModuleError = exceptions.ModuleError
LockError = exceptions.LockError
LockNotOwnedError = exceptions.LockNotOwnedError
WatchError = exceptions.WatchError
PubSubError = exceptions.PubSubError
SlaveError = exceptions.SlaveError
ClusterError = exceptions.ClusterError
ClusterDownError = exceptions.ClusterDownError
ClusterCrossSlotError = exceptions.ClusterCrossSlotError
MovedError = exceptions.MovedError
AskError = exceptions.AskError
TryAgainError = exceptions.TryAgainError

# ---------------------------------------------------------------------------
# Plan 10 — sync Redis façade
# ---------------------------------------------------------------------------

class Redis:
    """Drop-in sync façade compatible with redis-py's Redis class."""

    def __new__(
        cls,
        host: str = ...,
        port: int = ...,
        db: int | str = ...,
        password: str | None = ...,
        socket_timeout: float | None = ...,
        socket_connect_timeout: float | None = ...,
        socket_keepalive: bool | None = ...,
        socket_keepalive_options: dict[str, Any] | None = ...,
        connection_pool: Any | None = ...,
        unix_socket_path: str | None = ...,
        encoding: str = ...,
        encoding_errors: str = ...,
        charset: str | None = ...,
        errors: str | None = ...,
        decode_responses: bool = ...,
        retry_on_timeout: bool = ...,
        retry_on_error: list[Any] | None = ...,
        ssl: bool = ...,
        ssl_keyfile: str | None = ...,
        ssl_certfile: str | None = ...,
        ssl_cert_reqs: str | None = ...,
        ssl_ca_certs: str | None = ...,
        ssl_ca_path: str | None = ...,
        ssl_ca_data: Any | None = ...,
        ssl_check_hostname: bool = ...,
        ssl_password: str | None = ...,
        ssl_validate_ocsp: bool = ...,
        ssl_validate_ocsp_stapled: bool = ...,
        ssl_ocsp_context: Any | None = ...,
        ssl_ocsp_expected_cert: Any | None = ...,
        ssl_min_version: Any | None = ...,
        ssl_ciphers: str | None = ...,
        max_connections: int | None = ...,
        single_connection_client: bool = ...,
        health_check_interval: int = ...,
        client_name: str | None = ...,
        lib_name: str | None = ...,
        lib_version: str | None = ...,
        username: str | None = ...,
        retry: Any | None = ...,
        redis_connect_func: Any | None = ...,
        credential_provider: Any | None = ...,
        protocol: int = ...,
        cache: Any | None = ...,
        cache_config: Any | None = ...,
        event_dispatcher: Any | None = ...,
        **kwargs: Any,
    ) -> Redis: ...
    @classmethod
    def from_url(cls, url: str, **kwargs: Any) -> Redis: ...
    def close(self) -> None: ...
    def __enter__(self) -> Redis: ...
    def __exit__(self, *args: object) -> None: ...
    def pipeline(self, transaction: bool = ..., shard_hint: Any | None = ...) -> Any: ...
    def pubsub(self, **kwargs: Any) -> Any: ...
    def transaction(self, func: Any, *watches: Any, **kwargs: Any) -> Any: ...

    # String / key commands
    def get(self, name: str) -> bytes | None: ...
    def set(
        self,
        name: str,
        value: Any,
        ex: Any = ...,
        px: Any = ...,
        nx: bool = ...,
        xx: bool = ...,
        keepttl: bool = ...,
        get: bool = ...,
        exat: Any = ...,
        pxat: Any = ...,
    ) -> Any: ...
    def getex(
        self, name: str, ex: Any = ..., px: Any = ..., exat: Any = ..., pxat: Any = ..., persist: bool = ...
    ) -> bytes | None: ...
    def getdel(self, name: str) -> bytes | None: ...
    def copy(self, source: str, destination: str, db: int | None = ..., replace: bool = ...) -> bool: ...
    def incr(self, name: str, amount: int = ...) -> int: ...
    def incrby(self, name: str, amount: int = ...) -> int: ...
    def incrbyfloat(self, name: str, amount: float = ...) -> float: ...
    def decr(self, name: str, amount: int = ...) -> int: ...
    def decrby(self, name: str, amount: int = ...) -> int: ...
    def append(self, key: str, value: Any) -> int: ...
    def strlen(self, name: str) -> int: ...
    def mget(self, keys: list[str], *args: str) -> list[bytes | None]: ...
    def mset(self, mapping: dict[str, Any]) -> bool: ...
    def msetnx(self, mapping: dict[str, Any]) -> bool: ...
    def setrange(self, name: str, offset: int, value: Any) -> int: ...
    def getrange(self, key: str, start: int, end: int) -> bytes: ...
    def exists(self, *names: str) -> int: ...
    def delete(self, *names: str) -> int: ...
    def unlink(self, *names: str) -> int: ...
    def expire(self, name: str, time: int, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...) -> bool: ...
    def pexpire(self, name: str, time: int, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...) -> bool: ...
    def expireat(
        self, name: str, when: int, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> bool: ...
    def pexpireat(
        self, name: str, when: int, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> bool: ...
    def expiretime(self, name: str) -> int: ...
    def pexpiretime(self, name: str) -> int: ...
    def ttl(self, name: str) -> int: ...
    def pttl(self, name: str) -> int: ...
    def persist(self, name: str) -> bool: ...
    def rename(self, src: str, dst: str) -> bool: ...
    def renamenx(self, src: str, dst: str) -> bool: ...
    def type(self, name: str) -> bytes: ...
    def dump(self, name: str) -> bytes | None: ...
    def restore(
        self,
        name: str,
        ttl: int,
        value: Any,
        replace: bool = ...,
        absttl: bool = ...,
        idletime: int | None = ...,
        frequency: int | None = ...,
    ) -> bool: ...

    # List commands
    def lpush(self, name: str, *values: Any) -> int: ...
    def rpush(self, name: str, *values: Any) -> int: ...
    def lpushx(self, name: str, *values: Any) -> int: ...
    def rpushx(self, name: str, *values: Any) -> int: ...
    def lpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def rpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def lmove(self, first_list: str, second_list: str, src: str = ..., dest: str = ...) -> bytes | None: ...
    def lpos(
        self, name: str, value: Any, rank: int | None = ..., count: int | None = ..., maxlen: int | None = ...
    ) -> int | list[int] | None: ...
    def lrange(self, name: str, start: int, end: int) -> list[bytes]: ...
    def llen(self, name: str) -> int: ...
    def lrem(self, name: str, count: int, value: Any) -> int: ...
    def lindex(self, name: str, index: int) -> bytes | None: ...
    def lset(self, name: str, index: int, value: Any) -> bool: ...
    def linsert(self, name: str, where: str, refvalue: Any, value: Any) -> int: ...
    def ltrim(self, name: str, start: int, end: int) -> bool: ...
    def blpop(self, keys: Any, timeout: float = ...) -> tuple[bytes, bytes] | None: ...
    def brpop(self, keys: Any, timeout: float = ...) -> tuple[bytes, bytes] | None: ...
    def blmove(
        self, first_list: str, second_list: str, timeout: float, src: str = ..., dest: str = ...
    ) -> bytes | None: ...
    def blmpop(self, timeout: float, numkeys: int, *args: str, direction: str, count: int | None = ...) -> Any: ...
    def lmpop(self, num_keys: int, *args: str, direction: str, count: int | None = ...) -> Any: ...

    # Hash commands
    def hset(
        self,
        name: str,
        key: str | None = ...,
        value: Any | None = ...,
        mapping: dict[str, Any] | None = ...,
        items: list[Any] | None = ...,
    ) -> int: ...
    def hsetnx(self, name: str, key: str, value: Any) -> bool: ...
    def hmset(self, name: str, mapping: dict[str, Any]) -> bool: ...
    def hget(self, name: str, key: str) -> bytes | None: ...
    def hgetall(self, name: str) -> dict[bytes, bytes]: ...
    def hdel(self, name: str, *keys: str) -> int: ...
    def hincrby(self, name: str, key: str, amount: int = ...) -> int: ...
    def hincrbyfloat(self, name: str, key: str, amount: float = ...) -> float: ...
    def hkeys(self, name: str) -> list[bytes]: ...
    def hvals(self, name: str) -> list[bytes]: ...
    def hexists(self, name: str, key: str) -> bool: ...
    def hlen(self, name: str) -> int: ...
    def hmget(self, name: str, keys: list[str], *args: str) -> list[bytes | None]: ...
    def hscan(
        self,
        name: str,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        no_values: bool | None = ...,
    ) -> tuple[int, dict[bytes, bytes]]: ...
    def hrandfield(self, key: str, count: int | None = ..., withvalues: bool = ...) -> Any: ...
    def hexpire(
        self, name: str, time: int, *fields: str, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> list[int]: ...
    def hpexpire(
        self, name: str, time: int, *fields: str, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> list[int]: ...
    def hexpireat(
        self, name: str, when: int, *fields: str, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> list[int]: ...
    def hpexpireat(
        self, name: str, when: int, *fields: str, nx: bool = ..., xx: bool = ..., gt: bool = ..., lt: bool = ...
    ) -> list[int]: ...
    def httl(self, name: str, *fields: str) -> list[int]: ...
    def hpttl(self, name: str, *fields: str) -> list[int]: ...
    def hexpiretime(self, name: str, *fields: str) -> list[int]: ...
    def hpexpiretime(self, name: str, *fields: str) -> list[int]: ...
    def hpersist(self, name: str, *fields: str) -> list[int]: ...

    # Set commands
    def sadd(self, name: str, *values: Any) -> int: ...
    def srem(self, name: str, *values: Any) -> int: ...
    def smembers(self, name: str) -> _Set[bytes]: ...
    def sismember(self, name: str, value: Any) -> bool: ...
    def smismember(self, name: str, values: list[Any], *args: Any) -> list[bool]: ...
    def scard(self, name: str) -> int: ...
    def sunion(self, keys: list[str], *args: str) -> _Set[bytes]: ...
    def sunionstore(self, dest: str, keys: list[str], *args: str) -> int: ...
    def sinter(self, keys: list[str], *args: str) -> _Set[bytes]: ...
    def sinterstore(self, dest: str, keys: list[str], *args: str) -> int: ...
    def sintercard(self, numkeys: int, *keys: str, limit: int = ...) -> int: ...
    def sdiff(self, keys: list[str], *args: str) -> _Set[bytes]: ...
    def sdiffstore(self, dest: str, keys: list[str], *args: str) -> int: ...
    def smove(self, src: str, dst: str, value: Any) -> bool: ...
    def spop(self, name: str, count: int | None = ...) -> bytes | _Set[bytes] | None: ...
    def srandmember(self, name: str, number: int | None = ...) -> bytes | list[bytes] | None: ...
    def sscan(
        self, name: str, cursor: int = ..., match: str | None = ..., count: int | None = ...
    ) -> tuple[int, list[bytes]]: ...

    # Sorted set commands
    def zadd(
        self,
        name: str,
        mapping: dict[str, float],
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
        ch: bool = ...,
        incr: bool = ...,
    ) -> Any: ...
    def zrem(self, name: str, *values: Any) -> int: ...
    def zrange(
        self,
        name: str,
        start: Any,
        end: Any,
        desc: bool = ...,
        withscores: bool = ...,
        score_cast_func: Any = ...,
        byscore: bool = ...,
        bylex: bool = ...,
        rev: bool = ...,
        offset: int | None = ...,
        count: int | None = ...,
    ) -> list[Any]: ...
    def zrangebyscore(
        self,
        name: str,
        min: Any,
        max: Any,
        start: int | None = ...,
        num: int | None = ...,
        withscores: bool = ...,
        score_cast_func: Any = ...,
    ) -> list[Any]: ...
    def zrevrangebyscore(
        self,
        name: str,
        max: Any,
        min: Any,
        start: int | None = ...,
        num: int | None = ...,
        withscores: bool = ...,
        score_cast_func: Any = ...,
    ) -> list[Any]: ...
    def zrangebylex(
        self, name: str, min: Any, max: Any, start: int | None = ..., num: int | None = ...
    ) -> list[bytes]: ...
    def zrevrangebylex(
        self, name: str, max: Any, min: Any, start: int | None = ..., num: int | None = ...
    ) -> list[bytes]: ...
    def zrangestore(
        self,
        dest: str,
        name: str,
        start: Any,
        end: Any,
        byscore: bool = ...,
        bylex: bool = ...,
        rev: bool = ...,
        offset: int | None = ...,
        count: int | None = ...,
    ) -> int: ...
    def zincrby(self, name: str, amount: float, value: Any) -> float: ...
    def zcard(self, name: str) -> int: ...
    def zscore(self, name: str, value: Any) -> float | None: ...
    def zmscore(self, key: str, members: list[Any]) -> list[float | None]: ...
    def zrank(self, name: str, value: Any, withscore: bool = ...) -> int | tuple[int, float] | None: ...
    def zrevrank(self, name: str, value: Any, withscore: bool = ...) -> int | tuple[int, float] | None: ...
    def zremrangebyscore(self, name: str, min: Any, max: Any) -> int: ...
    def zremrangebylex(self, name: str, min: Any, max: Any) -> int: ...
    def zremrangebyrank(self, name: str, min: int, max: int) -> int: ...
    def zcount(self, name: str, min: Any, max: Any) -> int: ...
    def zlexcount(self, name: str, min: Any, max: Any) -> int: ...
    def zpopmin(self, name: str, count: int | None = ...) -> list[tuple[bytes, float]]: ...
    def zpopmax(self, name: str, count: int | None = ...) -> list[tuple[bytes, float]]: ...
    def bzpopmin(self, keys: Any, timeout: float = ...) -> tuple[bytes, bytes, float] | None: ...
    def bzpopmax(self, keys: Any, timeout: float = ...) -> tuple[bytes, bytes, float] | None: ...
    def zmpop(self, num_keys: int, *keys: str, direction: str, count: int | None = ...) -> Any: ...
    def bzmpop(self, timeout: float, num_keys: int, *keys: str, direction: str, count: int | None = ...) -> Any: ...
    def zrandmember(self, key: str, count: int | None = ..., withscores: bool = ...) -> Any: ...
    def zscan(
        self, name: str, cursor: int = ..., match: str | None = ..., count: int | None = ...
    ) -> tuple[int, list[tuple[bytes, float]]]: ...
    def zunion(self, keys: list[str], *args: Any, aggregate: str | None = ..., withscores: bool = ...) -> list[Any]: ...
    def zunionstore(self, dest: str, keys: list[str], *args: Any, aggregate: str | None = ...) -> int: ...
    def zinter(self, keys: list[str], *args: Any, aggregate: str | None = ..., withscores: bool = ...) -> list[Any]: ...
    def zinterstore(self, dest: str, keys: list[str], *args: Any, aggregate: str | None = ...) -> int: ...
    def zintercard(self, numkeys: int, *keys: str, limit: int = ...) -> int: ...
    def zdiff(self, keys: list[str], *args: Any, withscores: bool = ...) -> list[Any]: ...
    def zdiffstore(self, dest: str, keys: list[str], *args: Any) -> int: ...

    # Stream commands
    def xadd(
        self,
        name: str,
        fields: dict[str, Any],
        id: Any = ...,
        maxlen: int | None = ...,
        approximate: bool = ...,
        nomkstream: bool = ...,
        minid: Any | None = ...,
        limit: int | None = ...,
    ) -> Any: ...
    def xlen(self, name: str) -> int: ...
    def xrange(self, name: str, min: Any = ..., max: Any = ..., count: int | None = ...) -> list[Any]: ...
    def xrevrange(self, name: str, max: Any = ..., min: Any = ..., count: int | None = ...) -> list[Any]: ...
    def xread(self, streams: dict[str, Any], count: int | None = ..., block: int | None = ...) -> list[Any]: ...
    def xreadgroup(
        self,
        groupname: str,
        consumername: str,
        streams: dict[str, Any],
        count: int | None = ...,
        block: int | None = ...,
        noack: bool = ...,
    ) -> list[Any]: ...
    def xack(self, name: str, groupname: str, *ids: Any) -> int: ...
    def xdel(self, name: str, *ids: Any) -> int: ...
    def xgroup_create(
        self, name: str, groupname: str, id: Any = ..., mkstream: bool = ..., entriesread: int | None = ...
    ) -> bool: ...
    def xgroup_setid(self, name: str, groupname: str, id: Any, entriesread: int | None = ...) -> bool: ...
    def xgroup_destroy(self, name: str, groupname: str) -> int: ...
    def xgroup_createconsumer(self, name: str, groupname: str, consumername: str) -> bool: ...
    def xgroup_delconsumer(self, name: str, groupname: str, consumername: str) -> int: ...
    def xinfo_groups(self, name: str) -> list[Any]: ...
    def xinfo_stream(self, name: str, full: bool = ...) -> Any: ...
    def xinfo_consumers(self, name: str, groupname: str) -> list[Any]: ...
    def xtrim(
        self,
        name: str,
        maxlen: int | None = ...,
        approximate: bool = ...,
        minid: Any | None = ...,
        limit: int | None = ...,
    ) -> int: ...
    def xpending(self, name: str, groupname: str) -> Any: ...
    def xpending_range(
        self,
        name: str,
        groupname: str,
        min: Any,
        max: Any,
        count: int,
        consumername: str | None = ...,
        idle: int | None = ...,
    ) -> list[Any]: ...
    def xclaim(
        self,
        name: str,
        groupname: str,
        consumername: str,
        min_idle_time: int,
        message_ids: list[Any],
        idle: int | None = ...,
        time: int | None = ...,
        retrycount: int | None = ...,
        force: bool = ...,
        justid: bool = ...,
    ) -> list[Any]: ...
    def xautoclaim(
        self,
        name: str,
        groupname: str,
        consumername: str,
        min_idle_time: int,
        start_id: Any = ...,
        count: int | None = ...,
        justid: bool = ...,
    ) -> tuple[Any, list[Any], list[Any]]: ...
    def xsetid(self, name: str, id: Any, entriesadded: int | None = ...) -> bool: ...

    # Scripting / admin commands
    def eval(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def eval_ro(self, script: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def evalsha(self, sha: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def evalsha_ro(self, sha: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def script_load(self, script: str) -> bytes: ...
    def script_exists(self, *args: str) -> list[bool]: ...
    def script_flush(self, sync: bool = ...) -> bool: ...
    def fcall(self, function: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def fcall_ro(self, function: str, numkeys: int, *keys_and_args: Any) -> Any: ...
    def function_list(self, library: str | None = ..., withcode: bool = ...) -> list[Any]: ...
    def function_stats(self) -> Any: ...
    def function_dump(self) -> bytes: ...
    def function_restore(self, payload: bytes, policy: str = ...) -> bool: ...
    def function_delete(self, library_name: str) -> bool: ...
    def function_flush(self, mode: str = ...) -> bool: ...
    def scan(
        self, cursor: int = ..., match: str | None = ..., count: int | None = ..., type: str | None = ...
    ) -> tuple[int, list[bytes]]: ...
    def keys(self, pattern: str = ...) -> list[bytes]: ...
    def randomkey(self) -> bytes | None: ...
    def dbsize(self) -> int: ...
    def flushdb(self, asynchronous: bool = ...) -> bool: ...
    def flushall(self, asynchronous: bool = ...) -> bool: ...
    def info(self, section: str | None = ..., *args: str) -> Any: ...
    def config_get(self, pattern: str = ..., *args: str) -> dict[str, Any]: ...
    def config_set(self, name: str, value: Any = ..., *args: Any, **kwargs: Any) -> bool: ...
    def config_rewrite(self) -> bool: ...
    def config_resetstat(self) -> bool: ...
    def client_list(self, _type: str | None = ..., client_id: list[int] | None = ...) -> list[dict[str, Any]]: ...
    def client_info(self) -> dict[str, Any]: ...
    def client_id(self) -> int: ...
    def client_getname(self) -> bytes | None: ...
    def client_setname(self, name: str) -> bool: ...
    def client_kill(self, address: str) -> bool: ...
    def client_kill_filter(
        self,
        _id: int | None = ...,
        _type: str | None = ...,
        addr: str | None = ...,
        laddr: str | None = ...,
        skipme: bool | None = ...,
        username: str | None = ...,
        maxage: int | None = ...,
    ) -> int: ...
    def client_unpause(self) -> bool: ...
    def client_pause(self, timeout: int, all: bool = ...) -> bool: ...
    def client_no_evict(self, mode: str) -> bool: ...
    def object_encoding(self, key: str) -> bytes | None: ...
    def object_refcount(self, key: str) -> int | None: ...
    def object_idletime(self, key: str) -> int | None: ...
    def object_freq(self, key: str) -> int | None: ...
    def memory_usage(self, key: str, samples: int | None = ...) -> int | None: ...
    def ping(self, message: Any | None = ...) -> Any: ...
    def echo(self, value: Any) -> bytes: ...
    def wait(self, num_replicas: int, timeout: int) -> int: ...
    def waitaof(self, numlocal: int, numreplicas: int, timeout: int) -> tuple[int, int]: ...
    def time(self) -> tuple[int, int]: ...
    def lastsave(self) -> int: ...
    def bgsave(self, schedule: bool = ...) -> bool: ...
    def bgrewriteaof(self) -> bool: ...
    def debug_sleep(self, seconds: float) -> bool: ...
    def lock(
        self,
        name: str,
        timeout: float | None = ...,
        sleep: float = ...,
        blocking: bool = ...,
        blocking_timeout: float | None = ...,
        lock_class: Any | None = ...,
        thread_local: bool = ...,
    ) -> Lock: ...

class Lock:
    """Distributed lock backed by SET NX PX + Lua release/extend scripts."""

    def acquire(
        self,
        blocking: bool | None = ...,
        blocking_timeout: float | None = ...,
        token: bytes | None = ...,
    ) -> bool: ...
    def release(self) -> None: ...
    def extend(self, additional_time: float, replace_ttl: bool = ...) -> bool: ...
    def owned(self) -> bool: ...
    def locked(self) -> bool: ...
    def __enter__(self) -> Lock: ...
    def __exit__(self, *args: object) -> None: ...

def _facade_reset_warn_state() -> None: ...
