# Type stubs for the _driver Rust extension module.
#
# Hand-maintained until pyo3-stub-gen becomes viable for our setup; new
# commands (plans 03-09) extend this file as they land.

from collections.abc import Awaitable
from typing import Any

__version__: str

class RedisRsAwaitable:
    _asyncio_future_blocking: bool
    def __await__(self) -> RedisRsAwaitable: ...
    def __iter__(self) -> RedisRsAwaitable: ...
    def __next__(self) -> Any: ...
    def add_done_callback(
        self,
        fn_cb: Any,
        *,
        context: Any | None = ...,
    ) -> None: ...
    def cancel(self, msg: Any | None = ...) -> bool: ...
    def cancelled(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self) -> Any: ...
    def exception(self) -> Any: ...

class RedisRsDriver:
    @staticmethod
    def connect_standard(
        url: str,
        *,
        cache_max_size: int | None = ...,
        cache_ttl_secs: int | None = ...,
        ssl_ca_certs: bytes | None = ...,
        ssl_certfile: bytes | None = ...,
        ssl_keyfile: bytes | None = ...,
    ) -> RedisRsDriver: ...
    @property
    def connection_url(self) -> str: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def get(self, key: str) -> bytes | None: ...
    def aget(self, key: str) -> Awaitable[bytes | None]: ...
    # --- SET full matrix -------------------------------------------------
    def set(  # type: ignore[override]
        self,
        name: str,
        value: bytes,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        nx: bool = ...,
        xx: bool = ...,
        keepttl: bool = ...,
        get: bool = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
    ) -> bool | bytes | None: ...
    def aset(  # type: ignore[override]
        self,
        name: str,
        value: bytes,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        nx: bool = ...,
        xx: bool = ...,
        keepttl: bool = ...,
        get: bool = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
    ) -> Awaitable[bool | bytes | None]: ...

    # --- GET family ------------------------------------------------------
    def getex(
        self,
        name: str,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
        persist: bool = ...,
    ) -> bytes | None: ...
    def agetex(
        self,
        name: str,
        *,
        ex: int | None = ...,
        px: int | None = ...,
        exat: int | None = ...,
        pxat: int | None = ...,
        persist: bool = ...,
    ) -> Awaitable[bytes | None]: ...
    def getdel(self, name: str) -> bytes | None: ...
    def agetdel(self, name: str) -> Awaitable[bytes | None]: ...
    def getrange(self, name: str, start: int, end: int) -> bytes: ...
    def agetrange(self, name: str, start: int, end: int) -> Awaitable[bytes]: ...
    def setrange(self, name: str, offset: int, value: bytes) -> int: ...
    def asetrange(self, name: str, offset: int, value: bytes) -> Awaitable[int]: ...
    def strlen(self, name: str) -> int: ...
    def astrlen(self, name: str) -> Awaitable[int]: ...
    def append(self, name: str, value: bytes) -> int: ...
    def aappend(self, name: str, value: bytes) -> Awaitable[int]: ...

    # --- MGET / MSET / MSETNX --------------------------------------------
    def mget(self, keys: list[str]) -> list[bytes | None]: ...
    def amget(self, keys: list[str]) -> Awaitable[list[bytes | None]]: ...
    def mset(self, mapping: dict[str, bytes]) -> None: ...
    def amset(self, mapping: dict[str, bytes]) -> Awaitable[None]: ...
    def msetnx(self, mapping: dict[str, bytes]) -> bool: ...
    def amsetnx(self, mapping: dict[str, bytes]) -> Awaitable[bool]: ...

    # --- INCR / DECR family ---------------------------------------------
    def incr(self, name: str) -> int: ...
    def aincr(self, name: str) -> Awaitable[int]: ...
    def incrby(self, name: str, amount: int) -> int: ...
    def aincrby(self, name: str, amount: int) -> Awaitable[int]: ...
    def incrbyfloat(self, name: str, amount: float) -> float: ...
    def aincrbyfloat(self, name: str, amount: float) -> Awaitable[float]: ...
    def decr(self, name: str) -> int: ...
    def adecr(self, name: str) -> Awaitable[int]: ...
    def decrby(self, name: str, amount: int) -> int: ...
    def adecrby(self, name: str, amount: int) -> Awaitable[int]: ...

    # --- EXISTS / UNLINK -------------------------------------------------
    def exists(self, *names: str) -> int: ...
    def aexists(self, *names: str) -> Awaitable[int]: ...
    def unlink(self, *names: str) -> int: ...
    def aunlink(self, *names: str) -> Awaitable[int]: ...

    # --- EXPIRE family + TTL --------------------------------------------
    def expire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def aexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def pexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def apexpire(
        self,
        name: str,
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def expireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def aexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def pexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> bool: ...
    def apexpireat(
        self,
        name: str,
        when: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[bool]: ...
    def ttl(self, name: str) -> int: ...
    def attl(self, name: str) -> Awaitable[int]: ...
    def pttl(self, name: str) -> int: ...
    def apttl(self, name: str) -> Awaitable[int]: ...
    def expiretime(self, name: str) -> int: ...
    def aexpiretime(self, name: str) -> Awaitable[int]: ...
    def pexpiretime(self, name: str) -> int: ...
    def apexpiretime(self, name: str) -> Awaitable[int]: ...
    def persist(self, name: str) -> bool: ...
    def apersist(self, name: str) -> Awaitable[bool]: ...

    # --- RENAME / TYPE ---------------------------------------------------
    def rename(self, src: str, dst: str) -> None: ...
    def arename(self, src: str, dst: str) -> Awaitable[None]: ...
    def renamenx(self, src: str, dst: str) -> bool: ...
    def arenamenx(self, src: str, dst: str) -> Awaitable[bool]: ...
    def type(self, name: str) -> str: ...
    def atype(self, name: str) -> Awaitable[str]: ...
    def key_type(self, name: str) -> str: ...
    def akey_type(self, name: str) -> Awaitable[str]: ...

    # --- COPY ------------------------------------------------------------
    def copy(
        self,
        source: str,
        destination: str,
        *,
        db: int | None = ...,
        replace: bool = ...,
    ) -> bool: ...
    def acopy(
        self,
        source: str,
        destination: str,
        *,
        db: int | None = ...,
        replace: bool = ...,
    ) -> Awaitable[bool]: ...

    # --- DUMP / RESTORE --------------------------------------------------
    def dump(self, name: str) -> bytes | None: ...
    def adump(self, name: str) -> Awaitable[bytes | None]: ...
    def restore(
        self,
        name: str,
        ttl: int,
        value: bytes,
        *,
        replace: bool = ...,
        absttl: bool = ...,
        idletime: int | None = ...,
        frequency: int | None = ...,
    ) -> bool: ...
    def arestore(
        self,
        name: str,
        ttl: int,
        value: bytes,
        *,
        replace: bool = ...,
        absttl: bool = ...,
        idletime: int | None = ...,
        frequency: int | None = ...,
    ) -> Awaitable[bool]: ...
    def delete(self, *keys: str) -> int: ...
    def adelete(self, *keys: str) -> Awaitable[int]: ...
    def ping(self) -> bool: ...
    def aping(self) -> Awaitable[bool]: ...

    # --- LPUSH / RPUSH (variadic) ---------------------------------------
    def lpush(self, name: str, *values: bytes) -> int: ...
    def alpush(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def rpush(self, name: str, *values: bytes) -> int: ...
    def arpush(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def lpushx(self, name: str, *values: bytes) -> int: ...
    def alpushx(self, name: str, *values: bytes) -> Awaitable[int]: ...
    def rpushx(self, name: str, *values: bytes) -> int: ...
    def arpushx(self, name: str, *values: bytes) -> Awaitable[int]: ...

    # --- LPOP / RPOP / LRANGE / LLEN ------------------------------------
    def lpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def alpop(self, name: str, count: int | None = ...) -> Awaitable[bytes | list[bytes] | None]: ...
    def rpop(self, name: str, count: int | None = ...) -> bytes | list[bytes] | None: ...
    def arpop(self, name: str, count: int | None = ...) -> Awaitable[bytes | list[bytes] | None]: ...
    def lrange(self, name: str, start: int, end: int) -> list[bytes]: ...
    def alrange(self, name: str, start: int, end: int) -> Awaitable[list[bytes]]: ...
    def llen(self, name: str) -> int: ...
    def allen(self, name: str) -> Awaitable[int]: ...

    # --- LMOVE / LPOS ---------------------------------------------------
    def lmove(self, first_list: str, second_list: str, src: str, dest: str) -> bytes | None: ...
    def almove(self, first_list: str, second_list: str, src: str, dest: str) -> Awaitable[bytes | None]: ...
    def lpos(
        self,
        name: str,
        value: bytes,
        *,
        rank: int | None = ...,
        count: int | None = ...,
        maxlen: int | None = ...,
    ) -> int | list[int] | None: ...
    def alpos(
        self,
        name: str,
        value: bytes,
        *,
        rank: int | None = ...,
        count: int | None = ...,
        maxlen: int | None = ...,
    ) -> Awaitable[int | list[int] | None]: ...

    # --- LREM / LINDEX / LSET / LINSERT / LTRIM -------------------------
    def lrem(self, name: str, count: int, value: bytes) -> int: ...
    def alrem(self, name: str, count: int, value: bytes) -> Awaitable[int]: ...
    def lindex(self, name: str, index: int) -> bytes | None: ...
    def alindex(self, name: str, index: int) -> Awaitable[bytes | None]: ...
    def lset(self, name: str, index: int, value: bytes) -> None: ...
    def alset(self, name: str, index: int, value: bytes) -> Awaitable[None]: ...
    def linsert(self, name: str, where_: str, refvalue: bytes, value: bytes) -> int: ...
    def alinsert(self, name: str, where_: str, refvalue: bytes, value: bytes) -> Awaitable[int]: ...
    def ltrim(self, name: str, start: int, end: int) -> None: ...
    def altrim(self, name: str, start: int, end: int) -> Awaitable[None]: ...

    # --- LMPOP ----------------------------------------------------------
    def lmpop(
        self,
        keys: list[str],
        *,
        direction: str,
        count: int = ...,
    ) -> tuple[str, list[bytes]] | None: ...
    def almpop(
        self,
        keys: list[str],
        *,
        direction: str,
        count: int = ...,
    ) -> Awaitable[tuple[str, list[bytes]] | None]: ...

    # --- Blocking: BLPOP / BRPOP / BLMOVE / BLMPOP ----------------------
    def blpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def ablpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def brpop(self, keys: list[str], timeout: float) -> tuple[str, bytes] | None: ...
    def abrpop(self, keys: list[str], timeout: float) -> Awaitable[tuple[str, bytes] | None]: ...
    def blmove(
        self,
        first_list: str,
        second_list: str,
        src: str,
        dest: str,
        timeout: float,
    ) -> bytes | None: ...
    def ablmove(
        self,
        first_list: str,
        second_list: str,
        src: str,
        dest: str,
        timeout: float,
    ) -> Awaitable[bytes | None]: ...
    def blmpop(
        self,
        *,
        timeout: float,
        keys: list[str],
        direction: str,
        count: int = ...,
    ) -> tuple[str, list[bytes]] | None: ...
    def ablmpop(
        self,
        *,
        timeout: float,
        keys: list[str],
        direction: str,
        count: int = ...,
    ) -> Awaitable[tuple[str, list[bytes]] | None]: ...

    # --- Hashes (Plan 05) ------------------------------------------------
    def hget(self, key: str, field: str) -> bytes | None: ...
    def ahget(self, key: str, field: str) -> Awaitable[bytes | None]: ...
    def hset(
        self,
        key: str,
        *items: str | bytes,
        mapping: dict[str, bytes] | None = ...,
    ) -> int: ...
    def ahset(
        self,
        key: str,
        *items: str | bytes,
        mapping: dict[str, bytes] | None = ...,
    ) -> Awaitable[int]: ...
    def hsetnx(self, key: str, field: str, value: bytes) -> bool: ...
    def ahsetnx(self, key: str, field: str, value: bytes) -> Awaitable[bool]: ...
    def hmset(self, key: str, mapping: dict[str, bytes]) -> None: ...
    def ahmset(self, key: str, mapping: dict[str, bytes]) -> Awaitable[None]: ...
    def hgetall(self, key: str) -> dict[bytes, bytes]: ...
    def ahgetall(self, key: str) -> Awaitable[dict[bytes, bytes]]: ...
    def hmget(self, key: str, *fields: str) -> list[bytes | None]: ...
    def ahmget(self, key: str, *fields: str) -> Awaitable[list[bytes | None]]: ...
    def hdel(self, key: str, *fields: str) -> int: ...
    def ahdel(self, key: str, *fields: str) -> Awaitable[int]: ...
    def hexists(self, key: str, field: str) -> bool: ...
    def ahexists(self, key: str, field: str) -> Awaitable[bool]: ...
    def hlen(self, key: str) -> int: ...
    def ahlen(self, key: str) -> Awaitable[int]: ...
    def hkeys(self, key: str) -> list[bytes]: ...
    def ahkeys(self, key: str) -> Awaitable[list[bytes]]: ...
    def hvals(self, key: str) -> list[bytes]: ...
    def ahvals(self, key: str) -> Awaitable[list[bytes]]: ...
    def hincrby(self, key: str, field: str, amount: int) -> int: ...
    def ahincrby(self, key: str, field: str, amount: int) -> Awaitable[int]: ...
    def hincrbyfloat(self, key: str, field: str, amount: float) -> float: ...
    def ahincrbyfloat(self, key: str, field: str, amount: float) -> Awaitable[float]: ...
    def hrandfield(
        self,
        key: str,
        count: int | None = ...,
        withvalues: bool = ...,
    ) -> bytes | list[bytes] | list[tuple[bytes, bytes]] | None: ...
    def ahrandfield(
        self,
        key: str,
        count: int | None = ...,
        withvalues: bool = ...,
    ) -> Awaitable[bytes | list[bytes] | list[tuple[bytes, bytes]] | None]: ...
    def hscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        novalues: bool = ...,
    ) -> tuple[int, dict[bytes, bytes] | list[bytes]]: ...
    def ahscan(
        self,
        key: str,
        *,
        cursor: int = ...,
        match: str | None = ...,
        count: int | None = ...,
        novalues: bool = ...,
    ) -> Awaitable[tuple[int, dict[bytes, bytes] | list[bytes]]]: ...
    # Hash-field TTL family (Redis 7.4+)
    def hexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hpexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahpexpire(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hpexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> list[int]: ...
    def ahpexpireat(
        self,
        key: str,
        fields: list[str],
        time: int,
        *,
        nx: bool = ...,
        xx: bool = ...,
        gt: bool = ...,
        lt: bool = ...,
    ) -> Awaitable[list[int]]: ...
    def hexpiretime(self, key: str, fields: list[str]) -> list[int]: ...
    def ahexpiretime(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpexpiretime(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpexpiretime(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def httl(self, key: str, fields: list[str]) -> list[int]: ...
    def ahttl(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpttl(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpttl(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...
    def hpersist(self, key: str, fields: list[str]) -> list[int]: ...
    def ahpersist(self, key: str, fields: list[str]) -> Awaitable[list[int]]: ...

    # --- Test-only -----------------------------------------------------
    def _blocking_initialised(self) -> bool: ...

# Internal test helpers — exported but underscore-prefixed.
def _test_resolved_bytes(b: bytes) -> RedisRsAwaitable: ...
def _test_resolved_none() -> RedisRsAwaitable: ...
def _test_resolved_int(n: int) -> RedisRsAwaitable: ...
def _test_delayed_bytes(b: bytes, delay_ms: int) -> RedisRsAwaitable: ...
def _test_pending() -> RedisRsAwaitable: ...
def _test_dropped() -> RedisRsAwaitable: ...
def _test_error(msg: str) -> RedisRsAwaitable: ...
def _test_server_error(msg: str) -> RedisRsAwaitable: ...

class exceptions:
    class RedisError(Exception): ...
    class ConnectionError(RedisError): ...
    class TimeoutError(ConnectionError): ...
    class BusyLoadingError(ConnectionError): ...
    class AuthenticationError(ConnectionError): ...
    class AuthenticationWrongNumberOfArgsError(AuthenticationError): ...
    class MasterDownError(ConnectionError): ...
    class ResponseError(RedisError): ...
    class DataError(RedisError): ...
    class InvalidResponse(RedisError): ...
    class OutOfMemoryError(ResponseError): ...
    class NoScriptError(ResponseError): ...
    class ExecAbortError(ResponseError): ...
    class ReadOnlyError(ResponseError): ...
    class NoPermissionError(ResponseError): ...
    class ModuleError(ResponseError): ...
    class LockError(RedisError): ...
    class LockNotOwnedError(LockError): ...
    class WatchError(RedisError): ...
    class PubSubError(RedisError): ...
    class SlaveError(RedisError): ...
    class ClusterError(RedisError): ...
    class ClusterDownError(ResponseError, ClusterError): ...
    class ClusterCrossSlotError(ResponseError, ClusterError): ...
    class MovedError(ClusterError): ...
    class AskError(ClusterError): ...
    class TryAgainError(ClusterError): ...

# Top-level alias attrs (registered alongside the submodule):
RedisError = exceptions.RedisError
ConnectionError = exceptions.ConnectionError
TimeoutError = exceptions.TimeoutError
BusyLoadingError = exceptions.BusyLoadingError
AuthenticationError = exceptions.AuthenticationError
AuthenticationWrongNumberOfArgsError = exceptions.AuthenticationWrongNumberOfArgsError
MasterDownError = exceptions.MasterDownError
ResponseError = exceptions.ResponseError
DataError = exceptions.DataError
InvalidResponse = exceptions.InvalidResponse
OutOfMemoryError = exceptions.OutOfMemoryError
NoScriptError = exceptions.NoScriptError
ExecAbortError = exceptions.ExecAbortError
ReadOnlyError = exceptions.ReadOnlyError
NoPermissionError = exceptions.NoPermissionError
ModuleError = exceptions.ModuleError
LockError = exceptions.LockError
LockNotOwnedError = exceptions.LockNotOwnedError
WatchError = exceptions.WatchError
PubSubError = exceptions.PubSubError
SlaveError = exceptions.SlaveError
ClusterError = exceptions.ClusterError
ClusterDownError = exceptions.ClusterDownError
ClusterCrossSlotError = exceptions.ClusterCrossSlotError
MovedError = exceptions.MovedError
AskError = exceptions.AskError
TryAgainError = exceptions.TryAgainError
