# Type stubs for the _driver Rust extension module.
#
# Hand-maintained until pyo3-stub-gen becomes viable for our setup; new
# commands (plans 03-09) extend this file as they land.

from collections.abc import Awaitable
from typing import Any

__version__: str

class RedisRsAwaitable:
    _asyncio_future_blocking: bool
    def __await__(self) -> RedisRsAwaitable: ...
    def __iter__(self) -> RedisRsAwaitable: ...
    def __next__(self) -> Any: ...
    def add_done_callback(
        self,
        fn_cb: Any,
        *,
        context: Any | None = ...,
    ) -> None: ...
    def cancel(self, msg: Any | None = ...) -> bool: ...
    def cancelled(self) -> bool: ...
    def done(self) -> bool: ...
    def result(self) -> Any: ...
    def exception(self) -> Any: ...

class RedisRsDriver:
    @staticmethod
    def connect_standard(
        url: str,
        *,
        cache_max_size: int | None = ...,
        cache_ttl_secs: int | None = ...,
        ssl_ca_certs: bytes | None = ...,
        ssl_certfile: bytes | None = ...,
        ssl_keyfile: bytes | None = ...,
    ) -> RedisRsDriver: ...
    @property
    def connection_url(self) -> str: ...
    def cache_statistics(self) -> tuple[int, int, int] | None: ...
    def get(self, key: str) -> bytes | None: ...
    def aget(self, key: str) -> Awaitable[bytes | None]: ...
    def set(self, key: str, value: bytes, ttl: int | None = ...) -> None: ...
    def aset(self, key: str, value: bytes, ttl: int | None = ...) -> Awaitable[None]: ...
    def delete(self, *keys: str) -> int: ...
    def adelete(self, *keys: str) -> Awaitable[int]: ...
    def ping(self) -> bool: ...
    def aping(self) -> Awaitable[bool]: ...

# Internal test helpers — exported but underscore-prefixed.
def _test_resolved_bytes(b: bytes) -> RedisRsAwaitable: ...
def _test_resolved_none() -> RedisRsAwaitable: ...
def _test_resolved_int(n: int) -> RedisRsAwaitable: ...
def _test_delayed_bytes(b: bytes, delay_ms: int) -> RedisRsAwaitable: ...
def _test_pending() -> RedisRsAwaitable: ...
def _test_dropped() -> RedisRsAwaitable: ...
def _test_error(msg: str) -> RedisRsAwaitable: ...
def _test_server_error(msg: str) -> RedisRsAwaitable: ...

class exceptions:
    class RedisError(Exception): ...
    class ConnectionError(RedisError): ...
    class TimeoutError(ConnectionError): ...
    class BusyLoadingError(ConnectionError): ...
    class AuthenticationError(ConnectionError): ...
    class AuthenticationWrongNumberOfArgsError(AuthenticationError): ...
    class MasterDownError(ConnectionError): ...
    class ResponseError(RedisError): ...
    class DataError(RedisError): ...
    class InvalidResponse(RedisError): ...
    class OutOfMemoryError(ResponseError): ...
    class NoScriptError(ResponseError): ...
    class ExecAbortError(ResponseError): ...
    class ReadOnlyError(ResponseError): ...
    class NoPermissionError(ResponseError): ...
    class ModuleError(ResponseError): ...
    class LockError(RedisError): ...
    class LockNotOwnedError(LockError): ...
    class WatchError(RedisError): ...
    class PubSubError(RedisError): ...
    class SlaveError(RedisError): ...
    class ClusterError(RedisError): ...
    class ClusterDownError(ResponseError, ClusterError): ...
    class ClusterCrossSlotError(ResponseError, ClusterError): ...
    class MovedError(ClusterError): ...
    class AskError(ClusterError): ...
    class TryAgainError(ClusterError): ...

# Top-level alias attrs (registered alongside the submodule):
RedisError = exceptions.RedisError
ConnectionError = exceptions.ConnectionError
TimeoutError = exceptions.TimeoutError
BusyLoadingError = exceptions.BusyLoadingError
AuthenticationError = exceptions.AuthenticationError
AuthenticationWrongNumberOfArgsError = exceptions.AuthenticationWrongNumberOfArgsError
MasterDownError = exceptions.MasterDownError
ResponseError = exceptions.ResponseError
DataError = exceptions.DataError
InvalidResponse = exceptions.InvalidResponse
OutOfMemoryError = exceptions.OutOfMemoryError
NoScriptError = exceptions.NoScriptError
ExecAbortError = exceptions.ExecAbortError
ReadOnlyError = exceptions.ReadOnlyError
NoPermissionError = exceptions.NoPermissionError
ModuleError = exceptions.ModuleError
LockError = exceptions.LockError
LockNotOwnedError = exceptions.LockNotOwnedError
WatchError = exceptions.WatchError
PubSubError = exceptions.PubSubError
SlaveError = exceptions.SlaveError
ClusterError = exceptions.ClusterError
ClusterDownError = exceptions.ClusterDownError
ClusterCrossSlotError = exceptions.ClusterCrossSlotError
MovedError = exceptions.MovedError
AskError = exceptions.AskError
TryAgainError = exceptions.TryAgainError
